let ff={
   "para dejarte de amar": {
      "letra": "Para dejarte de amar\n\nvoy sufrir la vida entera\n\nseria imposible olvidar\n\ntodo el amor que yo te diera\n\npara dejarte de amar\n\nvoy adejar que yo me muera\n\npara olvidarme de ti\n\npara olvidarme de ti\n\nvoy adejar esta tierra\n\n\n\npara olvidar tus besos\n\nque fueron mi locura\n\nno te dire pa donde voy\n\nni en que lugar estoy\n\nsufriendo mi amargura\n\nme morire soñando\n\nque me quisiste un dia\n\nasi me ire sin el dolor\n\nque me dejo tu amor\n\nque lloro todavia\n\n\n\npara dejarte de amar\n\nsolo que el mar ya no existiera\n\nni las estrellas brillar\n\nni ver laflor en primavera\n\npara dejarte de amar\n\nvoy a dejar que yo me muera\n\npara olvidarme de ti\n\npara olvidarme de ti\n\nvoy a dejar esta tierra"
   },
   "mi virgen ranchera": {
      "letra": "(Para ti virgencita con mucho amor\n\nde todos tus hijos.)\n\n\n\nA tí virgencita , mi Guadalupana,\n\nyo  quiero ofrecerte un canto valiente,\n\nque México entero te brinda sonriente.\n\n\n\ny quiero decirte, lo que tu ya sabes,\n\nque México te ama, que nunca esta triste,\n\nporque de nombrarte, el alma se inflama.\n\n\n\nTu nombre es arrullo, y el mundo lo sabe,\n\nEres nuestro orgullo, mi México es tuyo,\n\nTu guardas la llave.\n\n\n\nQue viva la Reina, de los Mexicanos,\n\nla que con sus manos, sembró rosas bellas,\n\ny puso en el cielo, millares de estrellas.\n\n\n\nPor patria nos diste, este lindo suelo,\n\ny lo bendecirte, por que era tu anhelo,\n\ntener un santuario, cerquita del cielo."
   },
   "por amor": {
      "letra": "Por amor se han creado los hombres\n\nEn la faz de la tierra\n\nPor amor hay quien haya querido\n\nRegalar una estrella\n\n\n\nPor amor fue una vez al calvario\n\nCon una cruz acuesta\n\nAquel que también por amor\n\nEntregó el alma entera\n\n\n\nPor amor se confunden las aguas\n\nY en la fuente se besan\n\nY en las alas de las mariposas\n\nLos colores se crean\n\n\n\nPor amor ha existido en el mundo\n\nSiempre tanta belleza\n\nY el color de la naturaleza\n\nSe pintó por amor\n\n\n\nPor amor soy de ti y seré toda la vida\n\nMientras viva\n\nPor amor soy de ti\n\nPor amor, por amor, por amor\n\n\n\nPor amor\n\nuna noche cualquiera un amante se entrega\n\nPor amor\n\nEn un beso se calman unos labios que esperan\n\nPor amor\n\nYa no llevo las cruces que me dio el sufrimiento\n\nY por ti lo que fuera mi suerte se cambió por\n\namor"
   },
   "caminos de michoacan": {
      "letra": "Cariñito donde tu andas\n\ncon quien te estaras paseandooo\n\npresiento que no me engañas\n\npor eso te ando buscando\n\nvengo de tierras lejanas\n\nno mas por ti preguntandooo\n\n\n\nme dieron razon que andabas\n\nen las tierras michoacanas\n\nque de la piedad viajabas\n\npor rumbo del Aguacana\n\nte vieron cuando pasabas\n\npor zamora y nueva italia\n\n\n\ncaminos de michoacan\n\ny pueblos que voy pasando\n\nsi saben en donde esta\n\npor que me la estan negando\n\ndiganle que ando en Sahuayo\n\ny voy a ciudad de Hidalgo\n\n\n\nyo te seguire buscando\n\nen esas tierras tan bellas\n\nde zitacuaro a guencamo\n\nde apatzingan a morelia\n\nya me sueño acariciando\n\nesa carita morena"
   },
   "viva veracruz": {
      "letra": "Por aquí pasó volando una calandria amarilla,\n\nUna calandria amarilla por aquí pasó volando.\n\n\n\nUna calandria amarilla por aquí pasó volando.>\n\n\n\nEn su piquito llevaba una rosa de castilla\n\nQue el viento la deshojaba como blanca maravilla.\n\n\n\nQue el viento la deshojaba como blanca maravilla.>\n\n\n\nMaria Chuchena se fue a bañar,\n\nA orillas del río muy juntito al mar.\n\nMaria Chuchena se estaba bañando,\n\nY el techador por su casa pasando.\n\nY le decía: \n\nNi techo tu casa ni techo la mía,\n\nNo techo tu casa ni techo la mía,\n\nNi techo la casa de María García."
   },
   "el reventon": {
      "letra": "y vamos todos a gozar,\n\ncon alegria en el corazon,\n\nconmigo todos a bailar,\n\nal ritmo de este reventon...\n\n\n\nfelicidades,\n\nfelicidades,\n\nque bien la pases,\n\ny vamos a bailar...\n\n\n\ny mueve la caderita,\n\ny mueve tambien los pies,\n\ny date una vueltecita,\n\ny olvidate del estres...\n\n\n\nmenea la cinturita,\n\ny siguela sin parar,\n\nque no te falte en la vida,\n\namor y felicidad.\n"
   },
   "cancion de sayula": {
      "letra": "Sayula de mis amores\n\nCuando escucho esta canción\n\nHasta el pecho se me ensancha\n\nY me lleno de emoción\n\n\n\nSera porque regrese\n\nA visitar otra vez,\n\nA tu plaza, a tu santuario\n\nY al cerro de Santa Inés\n\n\n\nNunca olvido tu laguna\n\nY la quietud de sus playas\n\nTus cerros que te rodean\n\nDe colores de pitayas\n\n\n\nY tú valle de alfalfa\n\nDonde aprendí yo a vivir\n\nY en el que a Dios yo le pido\n\nLinda Sayula de mi alma\n\nQue me conceda morir\n\n\n\nFamosas son tus cajetas\n\nComo el ánima inmortal\n\nY no menos conocido\n\nEs tu lindo carnaval\n\n\n\nDonde siempre está el amor\n\nY te brindan su amistad\n\nCada una de las personas\n\nQue habitan esta ciudad."
   },
   "si dios me ayuda": {
      "letra": "dios me ayuda\n\nTe prometo vida mía\n\nVolver con tigo\n\nPara darte mucho mas\n\nTengo mil sueños\n\nPara compartir con tigo\n\nY a realizarnos\n\nDios me ayudara\n\n\n\nSolo te pido que me esperes\n\nUn poquito\n\nNo desesperes que muy pronto tu sabrás\n\nQue el sacrificio de estar lejos\n\nY no verte\n\nQue sacrificio para darte mucho mas\n\n\n\nTe extraño tanto vida mía tanto tanto\n\nQue hay momentos en que ya no puedo mas\n\nQuiero mirarte abrasarte y besarte\n\nDespués ser tuyo y volverme a regresar\n\n\n\nSi dios me ayuda\n\n\n\nSolo te pido que me esperes\n\nUn poquito ahora que tengo\n\nLa oportunidad\n\nSi dios me ayuda volveré con tigo vida\n\nPara quererte para darte mucho mas\n\n\n\nTe extraño tanto vida mía tanto tanto\n\nQue hay momentos en que ya no puedo mas\n\nQuiero mirarte abrasarte y besarte\n\nDespués ser tuyo y volverme a regresar\n\n\n\nSi dios me ayuda.\n"
   },
   "mexico en la piel": {
      "letra": "Como una mirada hecha en Sonora\n\nVestida con el mar de Cozumel\n\nCon el color del sol por todo el cuerpo\n\nAsi se lleva Mexico en la piel.\n\n\n\nComo el buen tequila de esta tierra\n\nO como un amigo de Yucatan\n\nY en Aguascaliente deshilados\n\nO una lana tejida en Teotitlan.\n\n\n\nAsi se siente Mexico, asi se siente Mexico,\n\nAsi como unos labios por la piel\n\nAsi te envuelve Mexico, asi te sabe Mexico\n\nY asi se lleva Mexico en la piel.\n\n\n\nComo ver la sierra de Chihuahua\n\nO artesania en San Miguel\n\nRemontar el cerro de la silla\n\nAsi se lleva Mexico en la piel.\n\n\n\nComo acompanarse con mariachi\n\nPara hacer llorar a esa cancion\n\nQue en el sur se toca con marimba\n\nY en el norte con acordeon."
   },
   "angelus": {
      "letra": "ANGELUS\n\n\n\nM: EL ANGEL DEL CIELO ANUNCIO A\n\nMARIA, QUE DIOS LA ESCOJIA;\n\nTODA LA TIERRA CALLABA,\n\nPORQUE UN LIRIO FLORECIA.\n\nT: ES  MI DIOS MI SALVADOR,\n\nME SALTA EL ALMA DE GOSO,\n\nPUES EL SANTO Y PODEROSO,\n\nHA HECHO EN MI MARAVILLAS,\n\nPOR SER PEQUEÑA Y SENCILLA\n\nM; COMO LO TENDRE SI NO ESTOY CASADA\n\nSOLO DESPOSADA\n\nCON EL SR, SAN JOSÉ\n\nMÁS EN MI  DIOS CREERE\n\nEL ANGEL CONTESTA NO TEMAS MARIA\n\nPARA SU VENIDA\n\nTE CUBRIRA CON SU MANTO\n\nEL ESPIRITU SANTO\n\nT: ES MI DIOS MI SALVADOR,\n\nME SALTA EL ALMA DE GOSO,\n\nPUES EL SANTO Y PODEROSO,\n\nHA HECHO EN MI MARAVILLAS,\n\nPOR SER PEQUEÑA Y SENCILLA\n\nM; SE INCLINO LA VIRGEN CON SANTO\n\nTEMOR, EN ADORACION Y RESPONDIO\n\nQUE ASI SEA SEGÚN EL SR, LO DESEA\n\nEL VERBO DIVINO ENCONTRO MORADA\n\nEL NIÑO AGUARDABA ENTRE TODAS\n\nLAS MUJERES UNA SOLA INMACULADA\n\nT: ES MI DIOS MI SALVADOR,\n\nME SALTA EL ALMA DE GOSO,\n\nPUES EL SANTO Y PODEROSO,\n\nHA HECHO EN MI MARAVILLAS,\n\nPOR SER PEQUEÑA Y SENCILLA\n"
   },
   "gloria": {
      "letra": "GLORIA\n\n\n\nT: GLORIA A NUESTRO DIOS\n\nEN LO ALTO DE LOS CIELOS, Y EN\n\nLA TIERRA PAZ A LOS HOMBRES POR EL AMADOS\n\n\n\nM: SR, TE ALABAMOS\n\nSR, TE BENDECIMOS\n\nTODOS TE ADORAMOS\n\nGRACIAS POR TU INMENSA GLORIA\n\n\n\nT: GLORIA A NUESTRO DIOS\n\nEN LO ALTO DE LOS CIELOS, Y EN\n\nLA TIERRA PAZ A LOS HOMBRES POR EL AMADOS\n\n\n\nM: TU ERES EL CORDERO\n\nQUE QUITAS EL PECADO\n\nTEN PIEDAD DE NOSOTROS\n\nY ESCUCHA NUESTRA ORACION.\n\n\n\nT: GLORIA A NUESTRO DIOS\n\nEN LO ALTO DE LOS CIELOS, Y EN\n\nLA TIERRA PAZ A LOS HOMBRES POR EL AMADOS\n\n\n\nM: TU SOLO ERES SANTO\n\nTÚ SOLO EL ALTISIMO\n\nCON EL ESPIRITU SANTO\n\nEN LA GLORIA DE DIOS PADRE\n\n\n\nT: GLORIA A NUESTRO DIOS\n\nEN LO ALTO DE LOS CIELOS, Y EN\n\nLA TIERRA PAZ A LOS HOMBRES POR EL AMADOS\n"
   },
   "bonito tecalitlan": {
      "letra": "Bonito Tecalitlán con sus mujeres hermosas,\n\nBonito Tecalitlán con sus mujeres hermosas,\n\nCuando me salí a bailar el Son de las mariposas,\n\nPero ay qué gusto me da de acordarme de ésas cosas.\n\nAy, ay, ay, Tecalitlán!\n\n\n\n\n\nA las dos de la mañana oí un mariachi tocar,\n\nA las dos de la mañana oí un mariachi tocar,\n\nY era el Mariachi Vargas que andaba por el portal,\n\nLlevándole serenata a las rosas del lugar.\n\nAy, ay, ay, Tecalitlán!\n\n\n\n\n\nYa con ésta me despido devisando para El Plán,\n\nYa con esta me despido devisando para El Plán,\n\nDe las muchachas bonitas de allá de Tecalitlán,\n\nPasando por Tamazula y también Ciudad Guzmán.\n\nAy, ay, ay, Tecalitlán!\n\n\n"
   },
   "nube de mar": {
      "letra": "Te alejaste de mí como nube de mar\n\nComo el agua del río que se aleja.\n\nMe dejaste un dolor que no sé mitigar\n\nY jamás te podré olvidar.\n\n\n\n¿Porque me dejas así?\n\n¿Que no ves lo que sufro por ti?\n\nNo quiero ser, no, no\n\nIlusión de amor y de dolor.\n\n\n\nAmor, porque me dejas en la bruma sin poderte amar\n\nBesar ésos labios que saben a miel.\n\nAmor, es imposible no adorarte cada instante más.\n\nA pesar que te hayas ido como nube de mar.\n"
   },
   "las mañanitas": {
      "letra": "Estas son las mañanitas\n\nQue cantaba el rey David\n\nHoy por ser día de tu santo\n\nTe las cantamos a ti\n\n\n\nDespierta, mi bien despierta\n\nMira que ya amaneció\n\nYa los pajarillos cantan\n\nLa luna ya se metió\n\n\n\nQue linda está la mañana\n\nEn que vengo a saludarte\n\nVenimos todos con gusto\n\nY placer a felicitarte\n\n\n\nEl día en que tu naciste\n\nNacieron todas las flores\n\nEn la pila del bautismo\n\nCantaron los ruiseñores\n\n\n\nYa viene amaneciendo\n\nYa la luz del día nos dio\n\nLevántate de mañana\n\nMira que ya amaneció\n\n\n\nDe las estrellas del cielo\n\nTengo que bajarte dos\n\nUna para saludarte\n\nOtra para decirte adiós\n\n\n\nVolaron cuatro palomas\n\nPor toditas la ciudades\n\n\n\nHoy por ser día de tu santo\n\nTe deseamos felicidades\n\nCon jasmines y flores\n\nHoy te vengo a saludar\n\nHoy por ser día de tu santo\n\nTe venimos a cantar\n"
   },
   "que alegria": {
      "letra": "QUE ALEGRÍA\n\n\n\nQUE ALEGRÍA CUANDO ME DIJERON:\n\nVAMOS A LA CASA DEL SEÑOR;\t  Do\n\nYA ESTÁN PISANDO NUESTROS PIES,\n\nTUS UMBRALES, JERUSALÉM.\n\n\n\nJerusalém está fundada\n\ncomo ciudad bien compacta,\n\nhalla suben las tribus\n\nlas tribus del Señor.\n\n\n\nSegún la costumbre de Israel\n\na celebrar el Nombre del Señor,\n\nen ella están los tribunales de justicia;\n\nen el palacio de David.\n\n\n\nDesead la paz a Jerusalém,\n\nvivan seguros los que Te aman;\n\nallá paz dentro de Tus muros\n\nen Tus palacios seguridad\n"
   },
   "si te perdiera": {
      "letra": "Si te perdiera,\n\nporque la vida cuando menos te lo esperas,\n\nTe da la espalda, te hace jugadas aunque tengas buena estrella,\n\nMe moriría de dolor si te perdiera,\n\nDespués de amarte la vida entera.\n\n\n\nSi te perdiera,\n\nTe llevarías los colores de mí vida,\n\nMe dejarías sin claridad, sin resplandor Y sin poemas,\n\nMe moriría de dolor, si te perdiera\n\nDespués de amarte la vida entera.\n\n\n\nSeria total mi soledad,\n\nSeria total mi desnudez,\n\nLa de los árboles heridos del otoño,\n\nCristales rotos en mi alma Y en mi noche pura escarcha,\n\nY el silencio por respuesta si te nombro.\n\nY ante mis ojos, no ver tus ojos,\n\nSolo vacío y soledad, si te perdiera...\n\nSi te perdiera..."
   },
   "por ti volare": {
      "letra": "Cuando vivo solo sueño un\n\nHorizonte falto de palabras\n\nEn la sombra y entre luces\n\nTodo es negro para mi mirada\n\nSi tú no estás, junto a mí, aquí.\n\n\n\nTú, en tu mundo\n\nSeparado del mío, por un abismo\n\nOye, llámame, yo volaré\n\nA tu mundo lejano.\n\n\n\nPor ti volaré\n\nEspera, que llegaré\n\nMi fin del trayecto eres tú\n\nPara vivirlo los dos.\n\n\n\nPor ti volaré\n\nPor cielos y mares, hasta tu amor\n\nAbriendo los ojos por fin\n\nContigo viviré.\n\n\n\nCuando estas lejana\n\nSueño un horizonte falto de palabras\n\nY yo sé que siempre estás ahí, ahí\n\nUna luna hecha para mí\n\nSiempre iluminada para mí,\n\nPor mí, por mí, por mí."
   },
   "sufriendo a solas": {
      "letra": "Quiero que mis amigos\n\nSin que se ofendan\n\nMe dejen solo\n\nPorque me da vergüenza\n\nLlorar con ellos mi sufrimiento\n\nAunque les agradezco que\n\nSe preocupen por mi dolor\n\nPienso que es preferible sufrir a solas\n\nMi cruel tormento\n\n\n\nHay tesurigiri del cielo\n\nDel infinito del más haya\n\nEl día que necesito que me reanimen\n\nQue me consuelen\n\nQuiero que se me borren todas las penas\n\nQue me dejo a ella quien yo adoraba\n\nY sin embargo me abandono\n\n\n\nCartas, retratos viejos hacen más triste\n\nMi soledad porque me traen recuerdos\n\nDe horas felices que no vendrán\n\n\n\nCruzan por mi memoria sus juramentos,\n\nSus falsedades que pa mí siempre\n\nFueron verdades pero que hoy traiciones son\n\n(Coro)\n\n\n\nQuiero que mis amigos\n\nSin que se ofendan\n\nMe dejen Solo!\n"
   },
   "querreque": {
      "letra": "Es buena la cervecita para el que esta desvelado,\n\nPara el que esta desvelado es buena la cervecita,\n\nYo prefiero un tequilita que lo mejo PA lo hinchado,\n\nQue lo mejor PA lo hinchado y asta lo panzón se quita,\n\n¡querreque!\n\n                                         \n\n Ay que bonito es tesón,\n\n     ¡querreque!\n\nPara bailarlo contigo,\n\n   ¡querreque!\n\n                     \n\n   Ay que bonito es tesón,\n\n     querreque!\n\nPara bailarlo contigo,\n\n\n\nDel güisqui y el aguardiente cual es el mejor licor,\n\nCual es el mejor licor del güisqui y el aguardiente,\n\nYo digo que el aguardiente por que es emborrachador,\n\nEmborracha al presidente también al gobernador,\n\n  ¡querreque!\n\n                                         \n\n Ay que bonito es tesón,\n\n     ¡querreque!\n\nPara bailarlo contigo,\n\n   ¡querreque!\n\n                     \n\n   Ay que bonito es tesón,\n\n     querreque!\n\nPara bailarlo contigo,\n\n              \n\nMe encontré con la huesuda sin saber que era la muerte,\n\nSin saber que era la muerte me encontré con la huesuda,\n\nMe dijo la testaruda no bebas el aguardiente,\n\nVas a morir de una cruda y amarga será tu suerte,\n\n    ¡querreque!\n\n                                         \n\n         Ay que bonito es tesón,\n\n     ¡querreque!\n\nPara bailarlo contigo,\n\n   ¡querreque!\n\n                     \n\n   Ay que bonito es tesón,\n\n     querreque!\n\nPara bailarlo contigo,"
   },
   "aleluya": {
      "letra": "T: ALELUYA, ALELUYA, ALELUYA\n\n\n\nM: LA DIESTRA DEL SR.\n\nHA HECHO PRODIGIOS\n\nLA DIESTRA DEL SR, ME HA SALVADO\n\n\n\nDOMINA CRISTO TODO EL UNIVERSO\n\nCRISTO SR, REYNA EN SU TRONO.\n"
   },
   "somos novios": {
      "letra": "Somos novios\n\nAutor: Armando Manzanero\n\n\n\nSomos novios\n\npues los dos sentimos mutuo amor profundo\n\ny con eso ya ganamos lo más grande\n\nde este mundo\n\nNos amamos, nos besamos\n\ncomo novios\n\nnos deseamos y hasta a veces sin motivo y\n\nsin razón, nos enojamos\n\nSomos novios\n\nmantenemos un cariño limpio y puro\n\ncomo todos\n\nprocuramos el momento más obscuro\n\nPara hablarnos\n\npara darnos el más dulce de los besos\n\nrecordar de qué color son los cerezos\n\nsin hacer mas comentarios, somos novios\n\n\n\nCoro:Para hablarnos\n\npara darnos el más dulce de los besos\n\n\n\nSolo; recordar de qué color son los cerezos\n\nsin hacer mas comentarios, somos novios\n"
   },
   "señor ten piedad": {
      "letra": "SEÑOR TEN PIEDAD\n\n\n\nM; SEÑOR TEN PIEDAD\n\nTEN PIEDAD DE NOSOTROS (2 VECES)\n\nT: (REP, 2 VECES)\n\n\n\nM; CRISTO, TEN PIEDAD,\n\nTEN PIEDAD DE NOSOTROS\n\nT; (REPITEN)\n\n\n\nM; CRISTO TEN PIEDAD\n\nT; TEN PIEDAD DE NOSOTROS\n\n\n\nM; SEÑOR TEN PIEDAD\n\nTEN PIEDAD DE NOSOTROS (2 VECES)\n"
   },
   "el pasajero": {
      "letra": "Ay, ay, ay, pasa, que pasa otro día\n\nAy, ay, ay, y mis tormentos no pasan\n\nGüerita del alma mía ay, ay, ay\n\nCuando me lleva a su casa\n\nPara estarme todo el día ay ay ay\n\nMe dice lo que le pasa ay, ay, ay, tiralarala\n\n\n\nAy, ay, ay, ya te he dicho que no siempre\n\nAy, ay, ay, las uvas junto al camino\n\nPor que pasa el pasajero ay, ay, ay\n\nSe corta el mejor racimo\n\nYa te he dicho que no siembres mi bien\n\nLas uvas junto al camino ay, ay, ay, tiralarala\n\n\n\n(Puente Musical)\n\n\n\nAy, ay, ay, ay, ay, bellísima jardinera\n\nAy, ay, ay, ay, ay, ay, ay, bellísima jardinera\n\nSi no me quieres hablar\n\nHazme una señal siquiera\n\nHazme una señal siquiera\n\nCon tu modo de mirar\n\nAy, ay, ay, ay, ay, ay, tiralarala\n\nAy, ay, ay, ay, ay, ay"
   },
   "el milagro de tus ojos": {
      "letra": "Cada vez que pienso en ti\n\nNace un mundo dulce y nuevo\n\nPorque brilla en tu mirar\n\nUna clara luz de ensueño\n\n\n\nQue me hace comprender\n\nLa nostalgia tibia de tu amor\n\nEs fuego que al arder\n\nCubre a los dos\n\n\n\nEn un cielo tan azul\n\nVuela hacia cualquier mañana\n\nPajaro multicolor\n\nBajo una mirada extraña\n\n\n\nQue me hace comprender\n\nLa nostalgia tibia de tu amor\n\nEs fuego que al arder\n\nCubre a los dos\n\n\n\nUn milagro brilla en su mirar\n\nTrayendo luz a mi vivir\n\nSiento entonces que van a estarllar\n\nEl sol y el mundo entero en nuestro amor\n\n\n\nEn un cielo tan azul\n\nVuela hacia cualquier mañana\n\nPajaro multi colr\n\nBajo una mirada extraña"
   },
   "el jarabe tapatio": {
      "letra": "En Jalisco se baila el Jarabe,\n\ncomo nadie lo sabe bailas,\n\nal compás de guitarras y bajos,\n\nel Jarabe se va a Zapatear\n\n\n\nEn Jalisco se baila el Jarabe,\n\ncomo nadie lo sabe bailar,\n\nal compás de guitarras y bajos,\n\nel Jarabe se va a Zapatear\n\n\n\nSentimiento de amor de Jalisco,\n\nque devora mi pecho en suspiro,\n\nyo creyendo que era un cariñito,\n\nun cariño vestido de amor\n\n(x2)\n\n\n\nEn Jalisco se baila el Jarabe,\n\ncomo nadie lo sabe bailar,\n\nal compás de guitarras y bajos,\n\nel Jarabe se va a Zapatear\n\n\n\nEn Jalisco se baila el Jarabe,\n\ncomo nadie lo sabe bailas,\n\nal compás de guitarras y bajos,\n\nel Jarabe se va a Zapatear\n"
   },
   "cordero de dios": {
      "letra": "CORDERO DE DIOS\n\n\n\nM: CORDERO DE DIOS\n\n\n\nT: CORDERO DE DIOS\n\n\n\nM: QUE QUITAS EL PECADO DEL MUNDO\n\nTEN PIEDAD DE NOSOTROS\n\n\n\nT: TEN PIEDAD DE NOSOTROS\n\n(TODO 3 VECES)\n\n\n\nX 3ª  VEZ\n\nT: DANOS LA PAZ.\n"
   },
   "que bonita es esta vida": {
      "letra": "Me gusta el olor que tiene la mañana  me gusta  el primer traguito de cafe\n\n\n\nsentir cuando el sol se asoma en mi ventana y me llena  la mirada de un hermoso amanecer\n\n\n\nme gusta  escuchar la paz de las montañas\n\nmirar los colores del atardecer\n\n\n\nsentir en mis pies la arena dela playa y lo dusce de la caña  cuando beso a mi mujer\n\n\n\nse seque el tiempo lleva  prisa paŽ  borrarme de la  lista pero yo le digo que\n\n\n\n(coro)\n\nhay........  que bonita es esta vida\n\n\n\n(bocalista)\n\n\n\naunque aveces duela tanto y apezar de los pezares siempre hay alguien que nos quiere siempre hay alguien que nos cuida\n\n\n\n(coro)\n\nhay hay hay hay\n\nque bonita es esta  vida"
   },
   "este vicio": {
      "letra": "Me encuentro tomando un trago aquí con mis amigos\n\nMe vieron muy pensativo y uno dijo que diablos te pasa\n\nNo me recuerdes amigo se marchó para siempre mi chata\n\nNo volveré a ver sus ojos ni a sentir su gran ternura\n\nNi aquel sabor de sus labios que me dio con tanta dulzura\n\nHay que tristeza tan grande solo dios sabe de mi amargura\n\n\n\nEste vicio que no deja nada\n\nDeja pura tristeza, llanto y amargura y la soledad\n\nEste vicio que cambio mi vida\n\nYa es demasiado tarde, los felices tiempos ya no volverán\n\n\n\n(Y Salustia compadre José pa que te acuerdes de navidad si señor)\n\n\n\nElla me dijo aquel día ya no puedo seguir a tu lado\n\nSe te esta llendo la vida y tú ni cuenta te has dado\n\nQue mala suerte la mía pues ya es tarde para remediarlo"
   },
   "santo": {
      "letra": "SANTO\n\n\n\nT: SANTO SANTO\n\nSR, DIOS DE LOS EJERCITOS  (3 VECES)\n\n\n\nM: LLENOS ESTAN LOS CIELOS\n\nY LA TIERRA DE TU GLORIA\n\n\n\nT: REPITEN\n\n\n\nT: HOSANA HOSANA\n\nHOSANA EN LAS ALTURAS (2 VECES)\n\n\n\nM: BENDITO EL QUE VIENE\n\nEN EL NOMBRE DEL SR,\n\n\n\nT: HOSANA HOSANA\n\nHOSANA EN LAS ALTURAS (2 VECES)\n"
   },
   "padre nuestro": {
      "letra": "Padre nuestro,\n\nque estás en el cielo,\n\nsantificado\n\nsea tu Nombre;\n\ndanos\n\nvenga tu reino;\n\nhágase tu voluntad\n\nasi en la tierra\n\ncomo en el cielo.\n\nDanos hoy nuestro pan\n\nde cada día;\n\ny perdona\n\nnuestras ofensas,\n\ncomo nosotros\n\nperdonamos\n\na los\n\nque nos ofenden;\n\nno nos dejes caer\n\nen tentación,\n\nPadre nuestro\n\nPadre nuestro\n\nlíbranos de todo  mal.\n"
   },
   "pero a donde vas": {
      "letra": "Como la paloma en paraje distante\n\nComo el sol lejano que anuncia la tarde\n\nComo la barquilla que va navegando\n\nSin vela y sin rumbo perdida en los mares\n\n\n\nAsí son las almas\n\nLas almas perdidas\n\nQue van caminando\n\nCon rumbo al abismo\n\nEn sombras de muerte\n\nPenumbra y dolor\n\n\n\nPero adónde vas\n\nPero adónde vas\n\nDetén tu cansado camino\n\nPorque de ese abismo\n\nJamás volverás\n\n\n\nPero adónde vas\n\nPero adónde vas\n\nEn Cristo hallaras el consuelo\n\nEl es el camino la vida y verdad\n\n\n\nComo las errantes estrellas del cielo\n\nComo aquella nube arrastrada del viento\n\nComo aquella higuera que Cristo maldijo\n\nQue nunca en la vida le dio de su fruto"
   },
   "rezare": {
      "letra": "Era una tarde fría y sin sol\n\nLa lluvia no dejaba de caer\n\nMis ojos no dejaban de llorar\n\nTe ibas para siempre de mi vida\n\nDespués de que te entregue mi corazón\n\nLa parte más bonita de mí ser\n\nLa parte más hermosa de mi vida\n\nTe fuiste sin decirme ni un adiós\n\n\n\nRezare\n\nPara que encuentres lo mejor que ahí en la vida\n\nPara que encuentres quien te quiera\n\nDe tal manera como yo te quise a ti\n\n\n\nRezare\n\nPorque tus sueños se hagan siempre realidad\n\nPara que nunca\n\nNunca sufras de tal manera como estoy sufriendo yo\n"
   },
   "me gusta cantar huapango": {
      "letra": "Me gusta cantar huapangos aunque yo nací en Jalisco\n\n(Coro; Me gusta cantar huapangos aunque yo nací en Jalisco)\n\nCuando canto este huapango al paisano lo dedico\n\n(Coro; Cuando canto este huapango al paisano lo dedico)\n\nQue orgullo es ser mexicano del meritito Jalisco\n\n\n\nBonitos son los huapangos los que nacen en la sierra\n\n(Coro; Bonitos son los huapangos los que nacen en la sierra)\n\nSe suelta la polvareda cuando los baila mi suegra\n\n(Coro; Se suelta la polvareda cuando los baila mi suegra)\n\nSe mira requeté contenta que hasta el alma se me alegra\n\n\n\nAyayay!\n\nQué bonito es el huapango pa bailarlo aquí contigo\n\nAyayay!\n\nPoder decirte cosas muy juntito en el oído\n\nQuererte a mi manera como nunca te han querido\n\nHuapangoooo\n\nQué bonito es el Huapangoooo!"
   },
   "pajarillo": {
      "letra": "Pitu pitu pitu pitu papam (3 vc.)\n\npitu pitu pitu pitu\n\n\n\npitu pitu pitu pitu papam (3 vc.)\n\npitu pitu pitu pitu\n\n\n\npajarillo pajarillo\n\nque vuelas por mi rivera\n\nporque no vuelas ahora que llego la primavera\n\nme dijiste que eras firme\n\ncomo la palma del llano\n\nsi la palma fuera firme\n\nno la quitara el gusano\n\nno la hacer volar el viento\n\nni la secara en verano\n\n\n\na mi me pueden llamar noel herrera pawer rallo\n\nsi me pagan buena visa\n\nno le pasa un pabalallo\n\nyo se quien anda de noche\n\ny me pongo tencitano\n\nyo se donde ladra el perro\n\ny se donde canta el gallo.\n\n\n\nY se cuando estan dormidas las muchachas de mi barrio.\n\n\n\n¡¡¡pajarillo!!!\n"
   },
   "algo contigo": {
      "letra": "Hace falta que te diga que me muero por tener algo contigo\n\nEs que no te has dado cuenta de lo mucho que me cuesta ser tu amigo\n\nYa no puedo acercarme a tu boca sin deseártela de una manera loca\n\nNecesito controlar tu vida, saber quién te besa y quien te abriga\n\n\n\nHace falta que te diga que me muero por tener algo contigo\n\nEs que no te has dado cuenta de lo mucho que me cuesta ser tu amigo\n\nYa no puedo continuar espiando día y noche tu llegar adivinando\n\nYa no sé con qué inocente escusa pasar por tu casa\n\nYa me quedan muy pocos caminos y aunque pueda parecerte desatinó\n\nYo quisiera no morirme  sin tener Algo Contigo\n\n\n\nYa no puedo continuar espiando día y noche tu llegar adivinando\n\nYa no sé con qué inocente escusa pasar por tu casa\n\nYa me quedan muy pocos caminos y aunque pueda parecerte desatinó\n\nYo quisiera no morirme  sin tener Algo Contigo\n"
   },
   "el son de la negra": {
      "letra": "Negrita de mis pesares\n\nOjos de papel volando\n\nNegrita de mis pesares\n\nOjos de papel volando\n\n\n\nA todos diles que si\n\nPero no les digas cuando\n\nAsi me dijiste a mi\n\nPor eso vivo penando .\n\n\n\nMUSICA\n\n\n\nCuando me traes a mi Negra\n\nQue la quiero ver aqui\n\nCon su rebozo de ceda\n\nQue le traje de Tepic .\n\n\n\nCuando me traes a mi Negra\n\nQue la quiero ver aqui\n\nCon su rebozo de ceda\n\nQue le traje de Tepic .\n"
   },
   "terrequeteque": {
      "letra": "Estando aserrando un palo si!! Haciendo terrequeteque no\n\nSolo aquel que no es cristiano si!! No tiene sus tres beleque no (* 2)\n\n\n\nAy la la la la, ay la la la la la la, estando aserrando una palo si!!\n\nHaciendo terrequeteque no\n\nAy la la la la, ay la la la la la la, Solo aquel que no es cristiano si!!\n\nNo tiene sus tres beleque no\n\n\n\nYa no me deja que duerma si!! ese terrequeteque o no\n\nEs la vieja de mi suegra si!! que me asusta y no la veo no (*2)\n\n\n\nAy la la la la, ay la la la la la la, Ya no me deja que duerma si!!\n\nese terrequeteque o no\n\nAy la la la la, ay la la la la la la, Es la vieja de mi suegra si!!\n\nque me asusta y no la veo no"
   },
   "alabare a mi señor": {
      "letra": "Alabare alabare alabare alabare\n\nalabare a mi señor\n\nAlabare alabare alabare alabare\n\nalabare a mi señor\n\n\n\nJuan vio el numero de los redimientos\n\ny todos alababan al señor\n\nunos cantaban otros oraban\n\ny todos alababan al senor\n\n\n\nAlabare alabare alabare alabare\n\nalabare a mi señor\n\nAlabare alabare alabare alabare\n\nalabare a mi señor\n\n\n\ntodos unidosalegres cantamos\n\ngloria y alabansasa al señor\n\ngloria el padre\n\ngloria al hijo\n\ngloria al espiriru dfe amor\n\n\n\nAlabare alabare alabare alabare\n\nalabare a mi señor\n\nAlabare alabare alabare alabare\n\nalabare a mi señor \n"
   },
   "el angel": {
      "letra": "Ángel de mis amores ya no me hagas padecer\n\nNo ves que me estoy muriendo por culpa de tu querer\n\nÁngel de mis amores ya no me hagas padecer\n\nNo ves que me estoy muriendo por culpa de tu querer\n\n\n\nDime que si dime que si\n\nDi que me quieres mucho compadécete de mi\n\nDime que si dime que si\n\nDi que me quieres mucho como yo te quiero a ti\n\n\n\nÁngel tienen tus ojos dos luceros que al brillar\n\nReflejan la luz del día cuando empiezo a despertar\n\nÁngel tienen tus ojos dos luceros que al brillar\n\nReflejan la luz del día cuando empiezo a despertar\n\n\n\nDime que si dime que si\n\nDi que me quieres mucho compadécete de mi\n\nDime que si dime que si\n\nDi que me quieres mucho como yo te quiero a ti\n"
   },
   "el triste": {
      "letra": "Este es el celo que yo padezco\n\nÉchame en tus brazos mi alma güerita si a caso yo lo merezco\n\nEste es el celo que yo padezco\n\nÉchame en tus brazos mi alma güerita si a caso yo lo merezco\n\n\n\n(Coro)\n\nAy no, no, no eso no tiene que ver\n\nAy si, si, si lloro por esa mujer\n\nAy no, no, no eso no tiene que ver\n\nAy si, si, si lloro por esa mujer\n\n\n\nQué triste estoy quiero llorar\n\nPero no por esos ojos mi vida por otros que andan por hay\n\nQué triste estoy quiero llorar\n\nPero no por esos ojos mi vida por otros que andan por hay\n\n\n\n(Coro)\n\n\n\nQué triste estoy porque te vas\n\nAy por el camino mi vida me la pagaras\n\nQué triste estoy porque me voy\n\nAy por el camino mi vida te diré quien soy\n\n\n\n(Coro)\n"
   },
   "que chulos ojos": {
      "letra": "que chulos ojos,\n\nlos que tiene\n\nesa linda joven\n\nque estoy mirando....\n\n\n\nque miradita\n\nesa que me esta matando\n\nyo la voy a convenser\n\n\n\nes tan bonita\n\nsu hermosura me a relumbrado\n\npor sus encantos\n\n\n\nes tan bonita\n\nyo le voy hablar de amores\n\nque chulada de mujer\n\n\n\nque cuerpo,que cara,que ojitos chiquitos\n\nojitos que provocan el fuego del amor\n\n\n\nque cuerpo,que cara que ojitos bonitos\n\nojitos que provocan el fuego mi amor\n\n\n\n\n\nque chulos ojos\n\nson luceros\n\nque alumbran\n\nmi alma cuando me miran\n\n\n\ncuando me miran\n\nparece que estoy soñando\n\ny no quiero amanecer"
   },
   "la fiesta del mariachi": {
      "letra": "La fiesta va comenzar\n\nadornen esos portones,\n\nla fiesta va comenzar\n\nadornen esos portones.\n\n\n\nYaa... va llegando el mariachi\n\ncantando sones\n\ncon sus guitarras\n\ny guitarrones...\n\npa que se alegren\n\ny que retocen\n\nlos corazones.\n\n\n\nYaa... va llegando el mariachi\n\ncantando sones\n\ncon sus guitarras\n\ny guitarrones...\n\npa que se alegren\n\ny que retocen\n\nlos corazones.\n\n\n\nAy lalala lalay\n\nay lalala lalay\n\nagarre su polla\n\npa que se baile\n\neste lindo son.\n\n\n\nAy lalala lalay\n\nay lalala lalay\n\nsaque polvadera\n\npa que retoce mi corazon.\n\n\n\nLa fiesta sigue bonita\n\ntoda llena de alegria,\n\nla fiesta sigue bonita\n\ntoda llena de alegria."
   },
   "pescador de hombres": {
      "letra": "Tu has venido a la oriila\n\nno has buscado a sabios, ni a ricos\n\ntan solo quieres que yo te siga\n\n\n\nSeñor, me has mirado a las ojos\n\nsonriendo, has dicho mi nombre\n\nen la rena, he dejado mi barca\n\njunto a ti, buscare otro mar\n\n\n\nTu necitas mis manos\n\nmis cansancios que a otros descansen\n\namor que quiero seguir amando\n\n\n\nSeñor, me has mirado a las ojos\n\nsonriendo, has dicho mi nombre\n\nen la rena, he dejado mi barca\n\njunto a ti, buscare otro mar\n\n\n\nTu sabes bien lo que quiero\n\nen mi barca no hay oro ni espadas\n\ntan solo redes y mi trabajo\n\n\n\nSeñor, me has mirado a las ojos\n\nsonriendo, has dicho mi nombre\n\nen la rena, he dejado mi barca\n\njunto a ti, buscare otro mar"
   },
   "que chulada de mujer": {
      "letra": "Que chulos ojos\n\nlos que tiene esa linda joven\n\nque estoy mirando\n\nque miradita\n\nesa que me esa matando\n\nyo la voy ha convencer\n\nes tan bonita\n\nsu hermosura me ha deslumbrado\n\npor sus encantos\n\nes tan bonita\n\nyo le voy ha hablar de amores\n\nque chulada de mujer\n\n\n\nQue cuerpo, que cara, que ojitos Chiquitos\n\nojitos que provocan el fuego del amor\n\nque cuerpo, que cara, que ojitos Bonitos\n\nojitos que provocan el fuego de mi amor\n\n\n\nQue chulos ojos\n\nson luceros que alumbran mi alma cuando me miran\n\ncuando me miran\n\nparece que estoy soñando\n\ny no quiero amanecer\n\n\n\nEs tan bonita\n\nsu hermosura me ha deslumbrado por sus encantos\n\nes tan bonita\n\nyo le voy ha hablar de amores\n\nque chulada de mujer"
   },
   "ojos tapatios": {
      "letra": "No hay ojos mas lindos,\n\nen la tierra mia,\n\nque los negros ojos, de la tapatia;\n\nmiradas que matan,\n\nardientes pupilas,\n\nnoche cuando duermen,\n\nluz cuando nos miran.\n\n\n\nEn noche de luna,\n\nperfume de azhares,\n\nen el cielo estrellas\n\ny tibios los aires,\n\ny tras de la reja,\n\ncubierta de flores,\n\nla novia que espera,\n\ntemblando de amores, siiiiii\n\n\n\nAl ver esos ojos\n\nque inquietos esperan,\n\napagan sus luces,\n\nlas blancas estrellas;\n\nlos aires esparcen aromas mejores,\n\ny todas las flores suspiran de amor.\n\n\n\nPor una mirada,\n\nde tan lindos ojos,\n\nestrellas y flores,\n\npadecen de enojos;\n\nlos aires suspiran,\n\nel cielo se apaga,\n\ny en el alma vaga,\n\nla queja,\n\nde amor.\n"
   },
   "el toro viejo": {
      "letra": "Por ay viene el caporal cayéndose de borracho (* 2)\n\ndiciéndole a los vaqueros: échenme ese toro gacho (* 2)\n\napa toro que allá va: lázalo!! ya lo alazé\n\namárrale hombre!! ya lo amarré\n\npiálalo!! ya lo pialé\n\ntúmbalo!! ya lo tumbé\n\néchale el pretal!! ya se lo eché\n\nasiérralo hombre!! ya lo aserré\n\nmóntale hombre!! ya le monté\n\ncapoteal hombre!! lo capoteé\n\néchalo pa' fuera!! yo ya lo eché\n\nllama a cabresto!! eso no sé\n\nSi tu no sabes te enseñaré...\n\nooo oooo ooooooooo\n\nmuchachos allá va el toro, no se lo dejen llegar\n\nporque ese toro es muy bravo, no los vaya a revolcar\n\nmuchachos allá va el toro, no se lo dejen llegar\n\nay les mandaré el capote pa' que lo puedan torear"
   },
   "la feria de las flores.": {
      "letra": "Me gusta cantarle al viento\n\nporque vuelan mis cantares,\n\ny digo lo que yo siento\n\npor toditos los lugares.\n\n\n\nAquí vine porque vine\n\na la feria de las flores,\n\nno hay cerro que se me empine\n\nni cuaco que se me atore.\n\n\n\nEn mi caballo retinto\n\nhe venido de muy lejos,\n\ny traigo pistola al cinto\n\ny con ella doy consejos.\n\n\n\nAtravesé la montaña\n\npa' venir a ver las flores;\n\naquí hay una rosa huraña,\n\nque es la flor de mis amores.\n\n\n\nY aunque otro quiera cortarla\n\nyo la devisé primero,\n\ny juro que he de robarla\n\naunque tenga jardinero.\n\n\n\nYo la he de ver trasplantada\n\nen el huerto de mi casa,\n\ny si sale el jardinero\n\n\n\npos a ver. . . a ver qué pasa.\n"
   },
   "camino real de colima": {
      "letra": "CAMINO REAL DE COLIMA\n\nCamino real de Colima, dicen que yo no lo sé.\n\nCamino real de Colima, dicen que yo no lo sé.\n\nComo no lo he de saber, si en el camino me crié.\n\nComo no lo he de saber, si en el camino me crié.\n\nCamino Real de Colima.\n\nMÚSICA\n\nCamino Real de Colima, tiene mil altos y bajos.\n\nCamino Real de Colima, tiene mil altos y bajos.\n\nEn compañía de mi chata, ando pasando trabajos.\n\nEn compañía de mi chata, ando pasando trabajos.\n\nCamino Real de Colima.\n\nMÚSICA\n\nTomo la pluma en la mano, para escribir y firmar.\n\nTomo la pluma en la mano, para escribir y firmar.\n\nLos trabajos que pasé, en ese camino real.\n\nLos trabajos que pasé, en ese camino real.\n\nTomo la pluma en la mano.\n\n(OTRAS ESTROFAS)\n\nCamino real de colima, dicen que yo no lo sé.\n\nCamino real de colima, dicen que yo no lo sé.\n\nEn compañía de mi chata, de rodillas lo andaré.\n\nEn compañía de mi chata, de rodillas lo andaré.\n\nCamino Real de Colima."
   },
   "a esa mujer": {
      "letra": "Se ha quedado en mi pensamiento un bello recuerdo\n\nde una mujer tan buena que siempre rezaba para\n\nprotegernos\n\nrepartia su besos repartia su llanto de aquellos\n\nmomentos\n\ny hoy pasan los años y ella sigue siempre con sus\n\nsentimientos\n\nla recuerdo tan altiva y bella dueña de mis sueños\n\nqueriendo como nadie toda su ternura iba repartiendo\n\na esos pedacitos que Dios le mandara para su alegrìa\n\ny hoy pasan los años y ella sigue siempre alumbrando\n\nel dìa\n\n\n\n(A esa mujer)\n\nla bendigo por ser buena y por ser lo mas grande\n\ndel mundo\n\n(A esa mujer)\n\nle venero por que fue la que me diò la vida la quiero"
   },
   "fiesta en jalisco": {
      "letra": "Saludos, esta es mi primera letra :D\n\nY como en todo el internet no está aquí con mucho gusto la pongo\n\n\n\nDe Cocula es el mariachi de Tecalitlán los sones\n\n\n\n-Música-\n\n\n\nTraigo un amor\n\nY lo traigo tan adentro\n\nQue hay momentos, que no siento\n\nDonde traigo el corazón\n\nTraigo un querer\n\nTan adentro está de mi alma\n\nHe perdido hasta la calma\n\nPor querer a esta mujer\n\n\n\nEl Jarabe zapateado de castilla salta a Valdo\n\ny el mariachi entusiasmado lanza sones sin parar\n\nel palenque se reboza en la sangre de un tapado\n\ny una china coquetona busca amores al cantar\n\n\n\n-Música-\n\n\n\nQue digan que estoy dormido\n\nY que me traigan aquí\n\nMéxico lindo y querido,\n\nSi muero lejos de ti"
   },
   "cancion mixteca": {
      "letra": "Canción Mixteca\n\n\n\nby N/A\n\nQue lejos estoy del suelo.\n\nDonde he nacido.\n\nInmensa nostalgia invade.\n\nMi pensamiento.\n\nY al verme tan solo y triste.\n\nCual hoja al viento.\n\nQuisiera llorar.\n\nQuisiera morir de sentimento.\n\n!Oh!tierra del sol.\n\nSuspiro por verte.\n\nAhora que lejos.\n\nyo vivo sin luz, sin amor...\n"
   },
   "sabes una cosa": {
      "letra": "Sabes una cosa\n\ntengo algo que decirte\n\ny no sé como empezar\n\na explica lo que te quiero cantar.\n\n\n\nSabes una cosa\n\nno encuentro las palabras\n\nni versos,rimas o prosa\n\nquizá con una rosa\n\nte lo pueda decir.\n\n\n\nSabes una cosa\n\nno se ni desde cuando\n\nllegaste de repente\n\nmi corazon lo empiesa a notar.\n\n\n\nSabes una cosa\n\nte quiero niña hermosa\n\ny te entrego en esta rosa\n\nla vida que me pueda quedar.\n\n\n\nDoy gracias al cielo\n\npor haberte conocido\n\npor haberte conocido\n\ndoy gracias al cielo.\n\n\n\nY le cuento a las estrellas\n\nlo bonito que sentí\n\nlo bonito que sentí\n\ncuando te conocí."
   },
   "ave maria": {
      "letra": "Ave maria\n\nGratia plena\n\nMaria, gratia plena\n\nMaria, gratia plena\n\nAve, ave dominus\n\nDominus tecum\n\nBenedicta tu in mulieribus\n\nEt benedictus\n\nEt benedictus fructus ventris\n\nVentris tuae, jesus.\n\nAve maria\n\n\n\nCoro AAAAAA\n"
   },
   "de repente": {
      "letra": "De repente\n\nComo un niño que se vuelve adolescente\n\nComo quien se vuelve loco\n\nY confunde su pasado y su presente\n\n\n\nComo si fuera brujería\n\nTu alegría me llenó completamente\n\nQue milagro fue vida mía\n\nQue manera tienes de amar\n\n\n\nDe repente\n\nMe moría por seguirte la corriente\n\nPor la noche y por el día\n\nTe veía en cada rostro de la gente\n\nVida mía\n\n\n\nDe repente\n\nCaminaste los caminos de mi mente\n\nLe quitaste las arrugas a mi frente\n\nY sembraste tu sonrisa en mi dolor\n\n\n\nComo si fuera brujería\n\nTu alegría me llenó completamente\n\nQue milagro fue vida mía\n\nQue manera tienes de amar"
   },
   "el caporal": {
      "letra": "Abran el corral muchachos que allá viene el caporal.\n\n(Abran el corral muchachos que allá viene el caporal).\n\nViene corriendo un novillo por ese camino real.\n\nHaber si logra alcanzarlo pa poderlo jinetear.\n\n¡uya! ¡uya!, ¡uya! ¡uya! ¡jah!\n\n(¡uya! ¡uya! ¡uya! ¡uya! ¡jah!)\n\nMÚSICA\n\nDicen que aquel caporal monta un caballo roano,\n\n(Dicen que aquel caporal monta un caballo roano)\n\nCon un lucero en la frente, y le llaman \"El Cubano\".\n\nPa correr es el primero, en las pistas y en los llanos.\n\n¡uya! ¡uya! ¡uya! ¡uya! ¡jah!\n\n(¡uya! ¡uya! ¡uya! ¡uya! ¡jah!)\n\nMÚSICA\n\nSoy del purito Jalisco mi semblante lo dirá,\n\n(soy de purito Jalisco mi semblante lo dirá)\n\nUso sombrero de charro y les brindo mi amistad.\n\nY cuando tiendo la mano, la doy con sinceridad.\n\n¡uya! ¡uya! ¡uya! ¡uya! ¡jah!,\n\n(¡uya! ¡uya! ¡uya! ¡uya! ¡jah!)\n"
   },
   "maquina 501": {
      "letra": "Makina 501....\n\nla ke korrio por sonora\n\npor eso los garroteros el ke no suspira llora...\n\n\n\nera un domingo señores...\n\nkomo a las 3 de la tarde\n\nestaba jesús garcia akariciando a su madre..\n\n\n\ndentro de pokos momentos..\n\nmadre tengo ke partir\n\ndel tren se escucha el silvato\n\nse aserka mi por venir..\n\n\n\ncuando llego a la estacion...\n\nel tren ya estaba silvando\n\ny un carro con dinamita se les estaba kemando..\n\n\n\nel fogonero le dicee..\n\njesús vamonos bajando mira ke el karro de atras\n\nya se nos viene kemando\n\n\n\njesús garcia le kontesta..\n\nyo pienso muy diferente yo no kiero\n\nser la kausa de ke muera\n\ntanta gente..."
   },
   "bala perdida": {
      "letra": "No es que no te quiera\n\nSi ya no te sigo besando\n\n(No es que no te quiera\n\nSi ya no te sigo besando)\n\n\n\nLa cruz no pesa lo que calan\n\nSon los filos\n\nCariño santo cariño santo\n\nYo no te dejo\n\nNi aunque me griten\n\nNi aunque me griten\n\nQue ya me estás\n\nQue ya me estás\n\nQue ya me estás acabando\n\n\n\nLas balas perdidas\n\nPegaron siempre en mi pecho\n\n(Las balas perdidas\n\nPegaron siempre en mi pecho)\n\n\n\nPero tus besos me inyectaron\n\nNueva vida\n\nBala perdida bala perdida\n\nBien haya el mauser\n\nQue te ha tronao\n\nQue te ha tronao\n\nPara acabar\n\nPara acabar\n\nPara acabar con mi vida"
   },
   "el ranchero afamado": {
      "letra": "Soy el ranchero afamado\n\nque de la sierra he bajado\n\nvengo a gastar mi dinero\n\nno les vengo a pedir fiado\n\ncuando llegue a la placita\n\nagarre la callesita\n\npreguntandole a la gente\n\ndonde vive Teresita\n\nLa gente me contestaba\n\nTeresita no esta aqui\n\nse la llevaron sus padres\n\npara San Luis Potosi\n\nensillenme mi caballo\n\ntambien mi yegua alazana\n\nsi no me llevo a Teresa\n\nsiempre me llevo a su hermana\n\nDonde esta mi carabina\n\nla pistola de mi hermano\n\nentrenle no sean cobardes\n\nse me hace que yo les gano\n\nCon mi sombrero de lado\n\ny mi guitarra cantando\n\nse despide de sus cuates\n\neste ranchero afamado.\n"
   },
   "20 años": {
      "letra": "Traigo un sentimiento pero muy\n\nadentro\n\nEn el mero fondo de mi corazon\n\nViejas decepciones\n\nQue me trajo el tiempo\n\nDe una historia negra\n\nDe un maldito amor\n\n\n\nLa mujer que quise me dejó\n\nPor otro\n\nLe seguí los pasos y maté a los dos\n\nYo no fuí culpable\n\nPorque estaba loco\n\nLoco por los celos\n\nLoco por su amor\n\n\n\nLas leyes de la tierra\n\nDictaron mi sentencia\n\nMe dieron sin clemencia\n\n20 años de prisión\n\nY aquí estoy prisionero\n\nMirando tras la reja\n\nUnicamente al cielo\n\nDonde se encuentra Dios\n\n\n\nLa mujer que quise me dejó\n\nPor otro\n\nLe seguí los pasos y maté a los dos\n\nYo no fuí culpable\n\nPorque estaba loco\n\nLoco por los celos\n\nLoco por su amor"
   },
   "carabina 30-30": {
      "letra": "Carabina 30-30\n\nque los rebeldes portaban\n\ny decían los maderistas\n\nque con ellas no mataban. (2)\n\n\n\nCon mi 30-30\n\nme voy a marchar\n\na engrosar las filas de la rebelión,\n\nsi mi sangre piden mi sangre les doy\n\npor los habitantes de nuestra nación.\n\n\n\nYa nos vamos pa' Chihuahua\n\nya se va tu negro santo\n\nsi me quiebra alguna bala\n\nve a llorarme al camposanto. (2)\n\n\n\nCon mi 30-30...\n\n\n\nGritaba Francisco Villa\n\n¿donde te hallas Argumedo?\n\nven parate aqui en el frente\n\ntú que nunca tienes miedo.\n\n\n\nGritaba Francisco Villa\n\n¿donde te hallas Argumedo?\n\nven parate aquí adelante\n\ntú que nunca tienes miedo.\n\n\n\nCon mi 30-30...\n"
   },
   "el corrido de santa amalia": {
      "letra": "En Santa Amalia vivía una joven\n\nLinda y hermosa como un jazmín\n\nElla solita se mantenía\n\nCosiendo ropa para vivir\n\n\n\nEl mal hermano le dice un día\n\n¡Ay! hermanita del corazon\n\nYa tu hermosura me tiene loco\n\nY tu marido quiero ser yo\n\n\n\nLa pobre joven quedó asombrada\n\nY en el instante le respondió\n\nMejor prefiero morir mil veces\n\nAntes que logres manchar mi honor\n\n\n\nEl mal hermano sacó el revolver\n\nY en el instante le disparó\n\nDándole un tiro en los sentidos\n\nQue todo el craneo le destrozó\n\n\n\nPor \"ay\" preguntan ¿quién había sido?\n\nLuego pregunta la autoridad\n\nVinieron gentes de todas partes\n\nA ver el crimen de aquél lugar\n\n\n\nEl juez declara que él había sido\n\nYo soy el hombre que la maté\n\nVete hermanita, vete tu al cielo\n\nQue yo en la carcel lo pagaré\n"
   },
   "los camperos": {
      "letra": "Llegaron los camperos\n\ncon sus guitarras\n\ncantando alegres.\n\nVienen por los esteros.\n\n\n\nEntre el zacate verde\n\nlejos se pierden\n\nen los potreros.\n\n¡Llegaron los camperos!\n\n\n\nCuando llegue la noche\n\nla luna va a alumbrar.\n\nPor el claro de la monte\n\nlejos se ven llegar.\n\n\n\nUna casa de adobe\n\nse esconde entre el breñal.\n\nAhí está mi campera\n\nla que me va a esperar.\n\n\n\nVengo desde muy lejos\n\npor eso traigo\n\na mis compañeros.\n\nLlegaron los camperos.\n\n\n\nCon éso les demuestro\n\nque mi cariño\n\nsí es verdadero.\n\n¡Llegaron los camperos!\n\n\n\nCuando llegue la noche...\n"
   },
   "el general": {
      "letra": "'Ora sí llegó\n\nsu mero mero general de división.\n\n¿Qui'ahi? Pos ¿qué pasó?\n\nPos ¿quiubo? Mi alma ya rejúntese con yo.\n\n\n\nNo, no soy rival,\n\npor Dios santito lo que quiero es vacilar\n\n'ora que vino a visitarles su aguerrido general.\n\n\n\nY aquel que no le guste el fuste\n\nque lo tire y monte a raiz.\n\n\n\nEse coronel\n\nmi capitán, mi sosteniente y vilmayor\n\nfirmes, que ahí voy yo\n\npasen revista luego luego al escuadrón.\n\n\n\nMúsicos de a real:\n\nLa Valentina quiero oírla pero ya.\n\nY aquel que no le guste el fuste\n\nque lo tire y monte a raiz.\n\n\n\nY aquel que no le guste el fuste\n\nque lo tire y monte a raiz."
   },
   "la muerte": {
      "letra": "Llega la muerte luciendo\n\nMil llamativos colores\n\nVen dame un beso pelona\n\nQue ando huérfano de amores\n\n\n\nEl mundo es una arenita\n\nY el Sol es una chispita\n\nY a mí me encuentran tomando\n\nCon la muerte en las cantinas\n\n\n\nNo le temo a la muerte\n\n(Más le temo a la vida)\n\nCómo cuesta morirse\n\n(Cuando el alma anda herida)\n\n\n\nDicen que van a asustarme\n\nLlevándome a tu presencia\n\nSi estás durmiendo en mi vida\n\nEs natural si despiertas\n\n\n\nSe va la muerte cantando\n\nPor entre la nopalera\n\n¿En qué quedamos pelona?\n\n¿Me llevas o no me llavas?\n\n\n\nNo le temo a la muerte\n\n(Más le temo a la vida)\n\nComo cuesta morirse\n\n(Cuando el alma anda herida)\n\n\n\nNo le temo a la muerte\n\nMás le temo a la vida\n"
   },
   "corrido de cananea": {
      "letra": "Voy a dar un pormenor\n\nde lo que a mí­ me ha pasado,\n\nque me han agarrado preso\n\nsiendo un gallo tan jugado.\n\n\n\nyo me fui para agua prieta\n\na ver quién me conocí­a\n\ny a las once de la noche\n\nme aprehendió la policia.\n\n\n\nme aprehendieron los gendarmes\n\nal estilo americano,\n\ncomo un hombre de delito,\n\ntodos con pistola en mano.\n\n\n\nla cárcel de cananea\n\nestá¡ situada en una mesa\n\ny en ella fui procesado\n\npor causa de mi torpeza.\n\n\n\ndespedida no la doy\n\nporque no la traigo agua\n\nse la deje al santo niño\n\ny al señor de mapimi.\n"
   },
   "el bandolero": {
      "letra": "Soy bandolero y me gusta ser vago\n\nnunca he vivido de un solo querer voy por el\n\nmundo vagando y sufriendo y nunca\n\nme he engrido con una mujer\n\nNo tengo amores querencia ninguna\n\nde los placeres me gusta vivir\n\ny a mis amigos les doy un consejo\n\nque sigan mi ejemplo\n\ny seran muy feliz\n\nMuchas mujeres hermosas yo he visto\n\nfalsas promesas de amor recibi\n\npero mi vida es andar por el mundo\n\nsolo les dejo un recuerdo de mi.\n"
   },
   "ya vas carnal": {
      "letra": "Ya vas carnal echame un rait en tu moto\n\nque esta pena no soporto ya no la puedo aguantar\n\ntu crees carnal\n\nque la chava que mas quiero se jugo con otro ñero\n\nque acabo de presentar\n\nya vas carnal si mi vida no retoña\n\ntodos los de mi coloña se van a burlar me cai\n\nya vas carnal\n\npero no vale la pena te juego hasta mi melena\n\nque esa chava volveraaaaaa\n\n\n\norale mi cuaiz  vamos a tupirle duro al chupe saludd\n\nya vas carnal\n\nyo agarrado de la moto\n\nella abrazado de otro\n\nquien sabe donde andaran\n\ntu crees carnal\n\ncamaras cuando lo supe\n\nle tupi reduro al chupe\n\ny no la puedo olvidar\n\nya vas carnal\n\nsi mi vida no retoña\n\ntodos los de mi coloña\n\nse van a burlar me caiiii\n\nya vas carnal\n\npero no vale la pena\n\nte juego hasta la melena hijo\n\nque esa chava volveraaaaaa\n\nya vas carnallll\n\n\n\n\n"
   },
   "no he venido a pedirte perdon": {
      "letra": "No he venido a pedirte perdon\n\nno me siento culpable de nada\n\nno he venido a pedir que me quieras\n\nni me siento prendido a tu amor\n\n\n\nCada vez que me aviento un alcohol\n\nya lo sabes que pierdo el sentido\n\nvoy a dar sin pensarlo contigo\n\naunque se que lo nuestro acabo\n\n\n\nNo hagas caso si me oyes cantar\n\nsi una noche te doy serenata\n\nes que le ando cantando a otra ingrata\n\ny borracho no supe ni a cual\n\n\n\nCada vez que me encuentres por hay\n\nno sera por que yo lo he querido\n\npuedes creer que el encuentro es casual\n\npero no quiero nada contigo...\n\n\n\nUyyyyyy ajajajaja, Esooooo!!!\n\n\n\nYo no soy como aquel que se va,\n\nque se va pero luego regresa\n\nbien me puedo morir de tristeza\n\npero yo nunca vuelvo jamass!"
   },
   "mi tierra es leon guanajuato": {
      "letra": "Mi tierra es Leon Guanajuato\n\nde oficio soy zapatero,\n\ny en el merito Irapuato\n\nNacio la joven que quiero\n\nella se crio entre las fresas\n\nyo entre pedazos de cuero.\n\n\n\nbonitas las de Celaya donde\n\nel amor se respeta,\n\nalla hay de todas las tallas\n\nmorenas, gueras y prietas\n\nde bocas muy coloradas\n\ncon el sabor a cajeta\n\n\n\ndesde el norte te mando un saludos\n\nGuanajuato mi estado querido\n\ny me gusta gritar con orgullo\n\nsoy de Leon y no lo echo al olvido\n\n\n\n( hay hay ahy Panza Verde )\n\n\n\nEn Moroleon tuve amores y amigos\n\nque son sinceros y de sus alrededores\n\nyo traigo gratos recuerdos, hasta en Dolores\n\nHilalgo, anduve un tiempo de arriero\n\n\n\ndesde el norte te mando un saludos\n\nGuanajuato mi estado querido\n\ny me gusta gritar con orgullo\n\nsoy de Leon y no lo echo al olvido\n"
   },
   "el rey de los caminos": {
      "letra": "soy el rey de los caminos\n\nsiempre vivo en carreteras\n\nen mi buen camion carguero\n\n\n\ny a segun sea mi destino\n\nen espejos y defensas\n\nvoy cambiando de letrero\n\n\n\nno le hace que sean casadas\n\nal cabo no soy celoso\n\nya llego por quien lloraban\n\n\n\nel amor de las dejadas\n\nel chofer mas cariñoso\n\nque las tiene alborotadas\n\n\n\ntengo mas suegras que las millas transitadas\n\nen cada pueblo voy dejando algun recuerdo\n\ngrandes o flacas, grandototas o chaparras\n\nyo soy parejo y voy haciendo lo que puedo\n\n\n\nyo soy un amor de todas\n\nexclusivo de ninguna\n\nsoy el rey de los caminos\n\n\n\ncorro a mas de 100 por hora\n\nmi camion es mi fortuna y\n\nlas mujeres mi destino"
   },
   "sin fortuna": {
      "letra": "Yo nací sin fortuna y sin nada,\n\ndesafiando al destino de frente,\n\nhasta el más infeliz me humillaba,\n\nignorándome toda la gente,\n\ny de pronto mi suerte ha cambiado,\n\ny de pronto me ví entre gran gente.\n\n\n\nVí a esa gente sentírse dichosa,\n\nfrente a un mundo vulgar y embustero,\n\ngente hipócrita, ruin, vanidosa,\n\nque de nada le sirve el dinero,\n\nque se muere lo mismo que el probre,\n\ny su tumba es el mismo agüjero.\n\n\n\nAhora voy por distintos caminos,\n\nvoy siguiendo tan solo al destino,\n\ny entre pobres me siento dichoso,\n\nsí amando doy mí amor entero,\n\ncon los pobres me quito el sombrero,\n\ny desprecio hasta el más poderoso."
   },
   "aguanta corazon": {
      "letra": "Corazon no es hora de llorar\n\naguanta tu penar dentro del pecho\n\ntu dolor tambien es mi dolor\n\naguanta corazon no seas tan necio\n\n\n\nhay corazon me lastima tu latir\n\ncorazon por que te empeñas\n\nen hacerme sufrir\n\n\n\nCorazon no es hora de llorar\n\naguanta tu penar dentro del alma\n\ntu dolor tambien es mi dolor\n\naguanta corazon mantente en calma\n\n\n\nhay corazon me lastima tu latir\n\ncorazon por que te empeñas\n\nen hacerme sufrir\n"
   },
   "los consejos de un padre": {
      "letra": "No codicies lo prohibido, no propagues lo nocivo, ni hagas mofa del dolor\n\nNunca obstruyas un camino que también sirve al vecino, ni te cobres un favor\n\nDar de ti las cosas buenas, dejara mejores huellas que una imagen ejemplar\n\nForma parte de la escuela que a tus hijos les conceda, un mañana sin igual\n\nLlena tu casa de amores, tu vida de amigos y se siempre fiel\n\nNo menosprecies al hombre, que no es de tu credo y color de tu piel\n\nDar una parte de tu agua tu pan y tu techo te hará muy feliz\n\nTodo lo bueno que hagas, no falta en la vida, quien lo haga por ti\n\n\n\nLucha por todo la que amas y en todo lo que hables, no mientas jamás\n\nUsa la mente y la calma y respeta al vecino, si quieres la paz\n\nNo le prometas a nadie, aquello que nunca, le vas a cumplir\n\nSon los consejos de un padre, que tiene deseos de enseñarte a vivir\n\nSon los consejos de un padre, que tiene deseos de enseñarte a vivir.\n"
   },
   "verdades amargas": {
      "letra": "Ya no quiero mirar lo que he mirado\n\natravez del cristal de la experienza\n\nel mundo, el mundo es un mercado\n\ndonde se compran voluntades y\n\nconcienzas, amigos es mentira no hay\n\namigos la verdadera amistad es ilucion\n\nhecha crese se va y desaparece\n\ncon los giros que da la situacion\n\n\n\namigos complasientes solo tienen\n\naquellos que disfrutan de oro y calma\n\nmas a quienes nos avata el infortunio\n\nsolo llevamos tristezas en el alma\n\n\n\nablado\n\nsi nos ven bien nos saludan nos invitan\n\npero si caemos solo por compromiso nos\n\nsaludan, la sociedad que aprecia su tesoro\n\nviste con saña al criminal mas si el puñal del\n\nasecino es de oro el jues enmudese y besa el puñal\n\nme han dado alivar yel y veneno y yel y veneno en\n\nrenconpensa doy y a nadiedeve erir lo que aqui digo\n\nen estas frases turvis y sin nonbre por que señido\n\na la verdad estoy y cundo veo a mi paso tanta infamia\n\ny que mis plantas pisas tanto lodo ganas me dan\n\nde maldesir la vida ganas me dan de maldesirlo todo\n\ny de rodillas pide perdon a dios jamas al hombre"
   },
   "Pobre Bohemio": {
      "letra": "Has que suene la lira mi hermano,\n\nhas que lloren las cuerdas sus quejas,\n\nacompaña mi llanto paisano,\n\nporque voy a contárte mis penas.\n\n\n\nEste pobre bohemio que mirás,\n\ntrovador de cantina en cantina,\n\nque con llanto te cuenta sus qüitas,\n\nque llorando te cuenta su vida.\n\n\n\nMuchas hembras tuve en mí camino,\n\nel dinero corrió por mis manos,\n\nmás de pronto cambió mí destino,\n\ny al momento me ví abandonado.\n\n\n\nEl dinero y las hembras no es nada,\n\nno me duele el haberlos pérdido,\n\nlo que sí me lastima en el alma,\n\nver dejado a mí pueblo querido.\n\n\n\n(música)\n\n\n\nEn mí pueblo dejé yo a mis padres,\n\na mí novia que tanto adoraba,\n\na correr yo me fuí por el mundo,\n\nsin saber lo que a mí me esperaba."
   },
   "paso a la reyna": {
      "letra": "Cuando la gente pregunta que\n\nsi a quien le dedico mis tiernas canciones,\n\nyo le contesto que aquella\n\nque endulza mi vida con bellas acciones\n\n\n\na la que en buenas o malas\n\nme brinda cariño sublime\n\ny eterno a la que vela conmigo\n\ncuidando la cuna del pequeño enfermo.\n\n\n\npara la bella señora que todas las tardes\n\nme espera amorosa.\n\npara la fiel compañera que quiso\n\nel destino que fuera mi esposa,\n\n\n\npara la reina de reinas que esta\n\npor encima de todas las cosas\n\npara la madre adnegada que no\n\ncambiaría por mil mariposas.\n\n\n\npaso a la reina señoras galantes,\n\ntiernas doncellas y fieles amantes,\n\nen este momento inclinen la frente\n\npor que la SEÑORA se encuentra presente."
   },
   "con rumbo al sur": {
      "letra": "Me voy en ese tren que va con rumbo al sur\n\ny quiero que esta noche me des mi despedia\n\nmuy pronto volvere primeramente dios\n\ndeseame buena suerte pedacito de mi vida\n\n\n\nllegando a la estacion del pueblo a donde voy\n\nte mando un telegrama pa que sepas mi destino\n\ntambien la direccion y calle donde este\n\ny asi nos escribimos aunque sea cada domingo\n\n\n\njamas me vallas a olvidar, asi me tarde yo en volver\n\nel dia que vuelvas por aqui, si voy para otras tierras\n\ntambien te llevare\n\n\n\nabrazate de mi y besame otra vez para llevar\n\nrecuerdos en mi pecho bien grabados, me marcho mas\n\nfeliz llevando tu calor y el dulce de tu boca\n\nsaboreando entre mis labios\n\n\n\njamas me vallas a olvidar, asi me tarde yo en volver\n\nel dia que vuelvas por aqui, si voy para otras tierras\n\ntambien te llevare...\n"
   },
   "desden": {
      "letra": "trasnochar\n\nes tu vida como un carrucel\n\nque por mas vueltas y vueltas\n\ndes en el mismo lugar\n\n\n\nser infiel\n\nvuelve a ser como en el cuento aquel\n\nque por mas buena que quieras ser\n\nsiempre mala has de ser\n\n\n\ntu\n\nme heriste con tus desden\n\ny olvidaste que yo tambien\n\ntengo un corazon\n\n\n\ntu\n\nme has hecho tanto esperar\n\ntu\n\nme has hecho tanto llorar\n\ncon desesperacion\n\n\n\nmira mi sufrir\n\noye mi alma gemir\n\nno ves que sin ti\n\nya no puedo vivir\n\n\n\nven\n\nquiero sentirte otra vez\n\nven a ahogar todo el padecer\n\nque me dio tu desden\n"
   },
   "amigo mio": {
      "letra": "\"Amigo Mio\"\n\n\n\nperdoname ke tedspierte\n\nen lo mas ondo de la noche\n\nke te utilice de paloma\n\namigo mio\n\n\n\nperdoname si estoy tomado\n\nya se ke tu lo has intentado\n\nke la palabra te ha negado\n\namigo mio\n\n\n\nhabla con ella y penetra en el fondo de su alma\n\nkuelga el telefono cruel ke me kita la calma\n\nhazla volver ve, y ve,  y dile ke la kiero\n\nvuelve otra vez y ve,y ve y dile ke no puedo\n\nseguir llorando,llorando de amor\n\nmuriendome en silencio\n\n\n\nprometele ke todo es cierto\n\nke no ocurrio nada de nada\n\nke ni sikiera me ha tenido\n\namigo mio\n\n\n\nprometele ke si regresa\n\nno habra rencores ni mentiras\n\nke se lo juro por mi vida\n\namigo mio"
   },
   "porque no fui tu amigo": {
      "letra": "Porqué no fuí tú amigo nadamás,\n\nporque tuve que darte el corazón,\n\nporque no fuí capaz de renunciar,\n\nporque no dije adiós.\n\n\n\nLo nuestro pudo ser para los dos,\n\ntan sólo una aventura y nada más,\n\npero te fuí queriendo más y más,\n\nsin escuchar la voz de la razón.\n\n\n\nPerdido en tu manera de besar,\n\njamás medí mis pasos,\n\ncontaba los minutos para estar,\n\nsoñando entre tus brazos.\n\n\n\nHoy sufro la vergüenza de saber,\n\nque aunque también me quieres, te me vas,\n\ny nunca dejaré de lamentar,\n\n¿Porqué no fuí tú amigo nada más?.\n\n\n\n(música)\n\n\n\nPerdido en tu manera de besar,\n\njamás medí mis pasos,\n\ncontaba los minutos para estar,\n\nsoñando entre tus brazos.\n\n\n\nHoy sufro la vergüenza de saber,\n\nque aunque también me quieres, te me vas,\n\ny nunca dejaré de lamentar,\n\n¿Porqué no fuí tú amigo nada más?.\n"
   },
   "lampara sin luz": {
      "letra": "Eres, una brujula sin rumbo\n\nun reloj sin manecillas\n\nuna biblia sin jesus\n\n\n\ncalles, las conoces metro a metro\n\ny bajo este pavimento\n\ntienes la tumba y la cruz\n\n\n\nel frio quemo ya tu altivez\n\ntu religion es la indecencia\n\nadmiro tu alma de hiel\n\npara ti el mundo nada cuenta\n\n\n\noro que engañaste a la que adoro\n\ny es aunque sus besos lloro\n\nuna lampara sin luz\n\n\n\n( hablado )\n\npor que si el hombre empeña\n\nsu anhelos poniendo a los\n\npies de una mujer su vida,\n\nes posible que no halla ni un destello\n\nque alumbre ni un poquitito\n\nsu ilusion perdida\n\n\n\nprecio que tan caro mi destino paga\n\nsabiendo que en mi corre la sangre herida\n\ny es el alma que razga un sentimiento\n\ny que canta y que llora, por que esta muy fria"
   },
   "abrazado de un poste": {
      "letra": "me dejaste abrazado de un poste esperandote\n\ny nunca llegaste me dijiste que alli te esperara\n\nbien recuerdo que me lo huraste ya muy noche me\n\nfui de la esquina y a tomar me meti a una\n\ncantina me sente y le pedi al cantinero una copa\n\ny despues la botella  junto a mi se arimo un\n\ncompanero que muy triste me dijo su pena el tambien\n\nse qedo en una esquina y a la cista tampoco fue ella\n\n\n\nconversamos le dije tu nombre direction y la\n\ncasa en que vives un cigaro me pidio aquel hombre cantinero otra\n\ncopa nos sierbes ya no sigas me dijo llorando es la misma que estuve esperando\n\n\n\n(ingrata donde andas).....\n\n\n\nconversamos le dije tu nombre direction y la casa en\n\nque vives un cigaro me pidio aquel hombre cantinero otra copa nos\n\nsirbes ya no sigaas me dijo llorando es la misma que estuve esperando \n"
   },
   "dimelo de frente": {
      "letra": "cuando sientas deseos de dejarme\n\nde una ves me lo dises de frente\n\nsi me dises tambien el  motivo\n\nya veras que sabre agradecerte\n\nno te vuelvo a estorbar en la vida\n\naunque sienta deveras perderte\n\n\n\nay un dicho que tal vez conoces\n\ny me queda a la pura medida\n\nporque yo al que se muere lo entierro\n\ny el amor que se va se me olvida\n\nno esque yo haya nacido de piedra\n\nse acostumbra uno a toda en la vida\n\n\n\nno ha de haber una gota de llanto\n\nel amor que de mi se despide\n\nno es orgullo ni nada de nada\n\npero puede que nunca me olvide\n\n\n\nvale mucho que estemos de acuerdo\n\nquiero todo muy bien entendido\n\nsi tu amor es deveras sincero\n\nyo tambien he de serlo contigo\n\ny al que juegue con cartas marcadas\n\nque le toque sufrir el castigo"
   },
   "el tabernero": {
      "letra": "Tabernero que idiotizas\n\ncon tu brebaje de fuego\n\nsigue llenando mi copa\n\nbuen amigo tabernero\n\n\n\nhasta verme como un loco\n\nrevolcandome en el suelo\n\nsigue llenando mi copa\n\ncon tu maldito veneno\n\n\n\nyo quiero matarme el alma\n\nque idiotiza mi cerebro\n\nunos se embriagan con vino\n\notros se embriagan con besos\n\n\n\ncomo yo no tengo amores\n\npues los que tuve murieron\n\nplacer encuentro en el vino\n\nque me brindas tebernero\n\n\n\nhablado:\n\ntodos los que son borrachos\n\nno es por el gusto de serlo\n\nsolo dios conose el alma\n\nque palpita en cada ebrio\n\nno vez mi copa vacia\n\nhecha vino tavernero\n\nque quiero matarme el alma\n\ncon tu maldito veneno"
   },
   "libro abierto": {
      "letra": "Dicen de mí,\n\nque yo he sido un libro abierto,\n\ndonde mucha gente ha escrito,\n\nno hagas caso nada es cierto.\n\n\n\nEn blanco está,\n\nnadie supo escribir nada,\n\nno dejaron ní una huella,\n\nnadie me importaba nada.\n\n\n\nMe importas tú,\n\ntu sí escribes muy bonito,\n\npara tí soy libro abierto,\n\nescribe en mí ¡te necesito!.\n\n\n\n(música)\n\n\n\nMe importas tú,\n\ntu sí escribes muy bonito,\n\npara tí soy libro abierto,\n\nescribe en mí ¡te necesito!.\n\n\n\nPara tí soy libro abierto,\n\nescribe en mí ¡te necesito!.\n"
   },
   "cargando con mi cruz": {
      "letra": "Con un pesar por dentro, mordiendo\n\nel sentimiento, con el remordimiento\n\nde no volverla a ver\n\n\n\npregunto las razones por que\n\ndos corazones tan llenos de ilusiones\n\nse dejan de querer\n\n\n\nhorrible desencanto, seguir sufriendo tanto\n\ny derramar el llanto por un lejano amor\n\nvivir desesperado vivir atormentado\n\nsentir que estas cansado tan lleno de dolor\n\n\n\ncargando con mi cruz, camino por el mundo\n\nsin cesar, como un judio herrante sin parar\n\nen sombras y sin luz\n\n\n\ncaido y sin amor, vacio ya por dentro\n\ny sin calor, hasta que dios al fin\n\nme de otra vez su amor\n\n\n\ncargando con mi cruz, camino por el mundo\n\nsin cesar, como un judio herrante sin parar\n\nen sombras y sin luz\n\n\n\ncaido y sin amor, vacio ya por dentro\n\ny sin calor, hasta que dios al fin\n\nme de otra vez su amor\n"
   },
   "nada contigo": {
      "letra": "No he venido a pedirte perdon\n\nno me siento culpable de nada\n\nno he venido a pedir que me quieras\n\nni me siento prendido a tu amor\n\n\n\ncada vez que me aviento un alcohol\n\nya lo sabes que pierdo el sentido\n\nvengo a dar sin pensarlo contigo\n\naunque se que lo nuestro acabo\n\n\n\nno hagas caso si me oyes cantar\n\nsi una noche rte doy serenata\n\nes que le ando cantado a otra ingrata\n\ny borracho no supe ni a cual\n\n\n\ncada vez que me encuentres por ahi\n\nno sera por que yo lo he querido\n\npuedes crees que el encuentro es casual\n\npero no quiero nada contigo\n\n\n\nyo no soy como aquel que se va, que se va\n\npero luego regresa, bien me puedo morir de\n\ntristeza, pero yo nunca vuelvo jamas"
   },
   "bohemio de aficion": {
      "letra": "Alejate de mi no quiero que me quieras\n\nyo soy otoño gris y tu eres primavera\n\ntu llevas en tu ser pureza de adeveras\n\nen cambio yo me pierdo con cualquiera\n\n\n\nalejate de mi yo en nada te convengo\n\nmi mundo de ilusion es todo lo que tengo\n\ninfiel en el amor lo traigo de abolengo\n\nrompiendo corazones me entretengo\n\n\n\nyo todo lo que tengo lo doy por las damas\n\ny nunca me entretengo a ver si me aman\n\nles doy mi corazon tan solo unas semanas\n\ny luego sin rencores dejo si se alejan si les da la gana\n\n\n\nme quito la camisa por un buen amigo\n\nhoy vivio millonario mañana mendigo\n\nmi dicha o mi dolor a nadie se lo digo\n\npor eso nadie sabe cuando estoy gozando cuando estoy herido\n\npor eso nadie sabe cuando estoy gozando cuando estoy herido"
   },
   "barrio pobre": {
      "letra": "NO SE PUEDE\n\nNO SE PUEDE TENER MAS EN LA VIDA\n\nNO SE PUEDE\n\n\n\nME DESPRECIAS\n\nPOR QUE VIVO EN BARRIO POBRE\n\nTU BIEN SABES\n\nQUE ES HERENCIA DEL DESTINO\n\nNO HE PODIDO\n\nCONQUISTAR NADA EN EL MUNDO\n\nNI LOS SUEÑOS\n\nQUE TUVE DESDE NIÑO\n\nTU HAS VIVIDO\n\nTODO EL TIEMPO EN LA OPULENCIA\n\nPERO NUNCA\n\nHAZ CONOCIDO UN BUEN CARIÑO\n\nPUES TUS PADRES DESCUIDARON DE TU VIDA\n\nY POR ESO NO TE CULPO\n\nNI TE RIO\n\nSI ALGUN DIA\n\nNECESITAS DE UN AMIGO,\n\nVEN CONMIGO DONDE ESTOY\n\nY YO TE ENSEÑO A QUERER\n\nCOMO A NADIE HABIAS QUERIDO\n\nY SABRAS QUE VIVIR\n\nNO ES SOLO UN SUEÑO\n\n\n\nCORO:\n\n\n\nEL DINERO Y LA BELLEZA\n\nSE ACABAN\n\nPERO EL AMOR\n\nSE QUEDA PA SIEMPRE PA SIEMPRE\n\nTE CREIAS\n\nLA MAS BELLA DE  LAS HEMBRAS,\n\nY YA VEZ\n\nQUE ENGAÑOSO ES EL DESTINO\n\nEL DINERO\n\nNO BORRA LO PASADO\n\nNI TE LIMPIA\n\nLAS HUELLAS DEL CAMINO\n\nCUANDO SOLA,\n\nTE ENCUENTRES ABATIDA\n\nY QUE TE HAYAN\n\nECHADO AL CRUEL OLVIDO\n\nRENEGANDO\n\nDE LUJOS Y RIQUEZAS\n\nDESEARAS\n\nEN BARRIO POBRE HABER NACIDO\n\nSI ALGUN DIA\n\nNECESITAS DE UN AMIGO\n\nVEN CONMIGO DONDE ESTOY\n\nY YO TE ENSEÑO\n\nA QUERER COMO A NADIE HABIAS QUERIDO\n\nY SABRAS QUE VIVIR\n\nNO SOLO ES UN SUEÑO.\n"
   },
   "me sacaron del tenampa": {
      "letra": "A CUANTAS VECES ME AN SACADO DEL TENAMPA\n\nYA BIEN BORRACHO Y CON UN NUDO EN LA GARGANTA\n\nVOY POR LA CALLE CANTANDO MIS CANCIONES\n\nY LOS MARIACHIS VAN PISANDO MIS TALONES\n\n\n\nLES PEDI 20, 30 Ò 5,000 CANCIONES\n\nY ME CANTARON ME CAI DE LA NUVE\n\nME REVOLQUE GRITE Y CANTE DE SENTIMIENTO\n\nME RECORDARON A UN AMOR QUE YO ANTES TUVE\n\n\n\nEN EL TENAMPA SE RECUERDAN MUCHAS COSAS\n\nY LOS MARIACHIS SON LOS AMOS Y SEÑORES\n\nTE TOMAS 4, 5, 20 Ò 30 COPAS\n\nY LAS CANCIONES TE RECUERDAN TUS AMORES\n\n\n\nLES PEDI 20, 30 Ò 5,000 CANCIONES\n\nY ME CANTARON ME CAI DE LA NUVE\n\nME REVOLQUE GRITE Y CANTE DE SENTIMIENTO\n\nME RECORDARON A UN AMOR QUE YO ANTES TUVE\n\n\n\nEN EL TENAMPA SE RECUERDAN MUCHAS COSAS\n\nY LOS MARIACHIS SON LOS AMOS Y SEÑORES\n\nTE TOMAS 4, 5, 20 Ò 30 COPAS\n\nY LAS CANCIONES TE RECUERDAN TUS AMORES\n"
   },
   "me cai de la nube": {
      "letra": "hay compadre como duelen estos golpes ,como duelen compadre\n\n\n\nMe cai de la nube en que andaba,\n\ncomo a 20 mil metros de altura,\n\npor poquito que pierdo la vida compadre,\n\nesa fue mi mejor aventura,por la suerte\n\ncai entre los brazos de una linda y hermosa criatura.\n\n\n\nMe tapo, con su lindo vestido,\n\ny corriendo pos a esconder me llevo compadre\n\nme colmo todo el cuerpo de besos\n\ny abrazada, pos conmigo lloro,\n\npreguntaba que yo le dijera\n\nque persona de alla me avento.\n\n\n\nNo le pude decir nada nada,\n\nsolamente pos pense en la maldad compadre,\n\nme subi, pos ya sabes hasta donde compadre,\n\ny tirarme a matar de verdad y olvidar a una\n\ningrata perdida que en mi cara me supo engañar."
   },
   "que tal si te compro": {
      "letra": "Nadie me puede ver en tu casa\n\nTodos me miran con gran desprecio\n\nDicen que yo no valgo la pena\n\nPa' merecer tu amor y tus besos\n\nPero que tal si te compro\n\nPara llevarte conmigo\n\nTe llevo lejos muy lejos\n\nPara perderme contigo\n\n\n\nYo siempre te e querido de veras\n\nNo se si tu también lo habrás hecho\n\nPero tus familiares de plano\n\nSiempre me ven con triste desprecio\n\nPero que tal si te compro\n\nPara llevarte conmigo\n\nTe llevo lejos muy lejos\n\nPara perderme contigo\n\n\n\nPero yo no te quiero hacer daño\n\nQuiero que seas feliz y dichosa\n\nPero tus familiares de plano\n\nNunca te dejaran ser mi esposa\n\nPero que tal si te compro\n\nPara llevarte conmigo\n\nTe llevo lejos, muy lejos para perderme contigo"
   },
   "te vas ángel mío": {
      "letra": "Te vas ángel mío ya vas a partir\n\ndejando mi alma herida\n\ny un corazón a sufrir\n\nte vas y me dejas un inmenso dolor\n\nrecuerdo inolvidable me ha quedado de tu amor\n\n\n\nPero hay cuando vuelvas no me hallaras aqui\n\niras a mi tumba y alli rezaras por mi\n\nveras unas letras escritas ahi\n\ncon el nombre y la fecha\n\ny el dia en que fallecí\n\n\n\nPero hay cuando vuelvas no me hallaras aqui\n\niras a mi tumba y alli rezaras por mi\n\nte vas ángel mío ya vas a partir\n\ndejando mi alma herida\n\ny un corazon a sufrir\n"
   },
  "dos amigos": {
     "letra":"Estos eran, dos amigos \n\nQue venían de Mapimi \n\nQue por no venirse de oquis \n\nRobaron Guanacevi\n\n\n\nEllos traiban, dos caballos \n\nUn oscuro y un jovero \n\nEn el oscuro cargan ropa \n\nY en el jovero el dinero\n\n\n\nTambién traiban, maquinaria \n\nY muy buenas bacterias \n\nPara desclavar los rieles \n\nY hacer los cambios de vía\n\nMartín le dice a Jose\n\n\n\nNo te pongas amarillo \n\nVamos a robar el tren \n\nQue viene de Vermejillo\n\nAmarillo no me pongo\n\n\n\nAmarillo es mi color \n\nHe robado trenes grandes \n\nY maquinas de vapor\n\nValgame el santo ninito\n\n\n\nYa agarraron a Jose \n\nEn la esquina del mercado \n\nLo ataron y se les fue\n\nSeria por sus oraciones\n\n \n\nQue su madre le rezaba \n\nSeria por su buena suerte \n\nQue a Jose no le tocaba"
  },
  "dos gotas de agua": {
     "letra":"Que voy a hacer contigo,\n\nte sueño todas las noches,\n\nte traigo siempre conmigo\n\ny no te puedo olvidar.\n\n\n\n\n\nQue voy a hacer contigo,\n\nmi vida ya es un martirio,\n\nparece ser mi destino\n\nquererte sin descansar.\n\n\n\n\n\nMi vida se está acabando\n\ny no quieres darte cuenta,\n\nnomás porque eres igual que yo.\n\nTe gusta verme rendido\n\nsabiendo que yo pido\n\npiedad, clemencia\n\nni compasión.\n\n\n\n\n\nCORO\n\n\n\n\n\nDos gotas de agua,\n\ncristalinas y transparentes,\n\nson nuestras almas,\n\ntan iguales y tan diferentes.\n\n\n\n\n\nSomos dos gotas de agua,\n\nque no sabemos rodar,\n\npero cuando nos juntemos\n\nnadie en la vida nos va separar."
  },
  "la lampara": {
     "letra":"Hay de mi...\n\nque por un amor\n\nal que yo perdi\n\nhay dios mio ¿que hare yo?\n\nprefiero morir...\n\ny no existir\n\ny no existir...\n\ncual marchita flor...\n\n\n\n\n\n(Coro)\n\n\n\nTristes lloran mis cansados parpados\n\nal mirar que si apago la lampara\n\nque alumbrara mi amor con grande animo\n\ncuando tu te mostrabas mas candido...\n\npero al ver que eres tan antipatico\n\ny conmigo te muestras venebolo\n\nmis pupilas ya no encuentran lagrimas\n\npara llorar...\n\nmi soledad.\n\n\n\n\n\n(Coro)\n\n\n\nTristes lloran mis cansados parpados\n\nal mirar que si apago la lampara\n\nque alumbrara mi amor con grande animo\n\ncuando tu te mostrabas mas candido...\n\npero al ver que eres tan antipatico\n\ny conmigo te muestras venebolo\n\nmis pupilas ya no encuentran lagrimas\n\npara llorar...\n\nmi soledad."
  },
  "diferencias sociales": {
     "letra":"No pensaba decidirme\n\npero al ver\n\nque te vas para siempre\n\nhe querido que esta noche\n\nbien grabada se quede en tu mente\n\n\n\n\n\nMis mariachis te despiden\n\nmis guitarras bendicen tu suerte\n\nno hay en mi\n\nningún reproche\n\nporque se que no es culpa de mi\n\n\n\n\n\nSin mirar diferencias sociales\n\nnos tuvimos amor de verdad\n\ncorazón\n\npero son convencionales\n\ny al mirar que no somos iguales\n\nnos señalan lugares distantes\n\npara ya no podernos mirar\n\n\n\n\n\n(Adiós Amor)\n\n\n\n\n\nBrindaré por el cariño\n\nque por mi solamente has tenido\n\nporque el tiempo y la distancia\n\nno lo llenen de polvo y olvido"
  },
  "puñales de fuego": {
     "letra":"Se alejó de mi lado la ingrata\n\nque tanto adoraba,\n\nfue mentira el cariño sincero\n\nque un día me juró.\n\n\n\nDesde entonces se ha vuelto\n\nde fuego mi sangre en la venas\n\ndesde entonces la sombra del árbol\n\ntambién se acabó.\n\n\n\nDe tristeza las aves del campo\n\nse van desterrando\n\nel arroyo donde ella lavaba\n\nun día se secó.\n\n\n\nEl jacal con paredes de adobe\n\ndonde ella vivía\n\nuna noche después de su ausencia\n\ntambién se quemó.\n\n\n\nLos caminos que juntos nos vieron\n\nse llenan de espinas,\n\npor las noches me dicen los vientos\n\nque no volverá.\n\n\n\nHa mandado clavar en mi pecho\n\npuñales de fuego,\n\nsin embargo la sigo queriendo\n\ny la voy a esperar."
  },
  "pideme": {
     "letra":"Pídeme.\n\nQue toque el sol con las manos\n\nó que cuente las arenas.\n\nel desierto al caminar\n\npero no me pidas\n\n\n\npideme\n\nQue el tiempo todo se detenga.\n\nQue deje ya de respirar.\n\nQue no gire la tierra.\n\n\n\npideme\n\nQue muevas las montañas\n\nò que me ponga a volar.\n\nque baje a lo profundo de las aguas\n\nde la mar\n\n\n\nPero no me pidas.\n\nPero no me pidas.\n\n\n\npideme\n\n\n\npideme\n\nQue el tiempo todo se detenga.\n\nQue deje ya de respirar.\n\nQue no gire la tierra.\n\n\n\npideme\n\nQue muevas las montañas\n\nò que me ponga a volar.\n\nque baje a lo profundo de las aguas de la mar.\n\n\n\npideme mi vida...\n\n\n\npero no me pidas\n\nque te deje yo de amar..."
  },
  "te he prometido": {
     "letra":"Te he prometido que te he de olvidar\n\ncuanto has querido y yo te supe dar,\n\nsolo y herido asi me dejas,\n\nsabiendo que mañana iras con otro al altar\n\n\n\nLloraras, Lloraras por tu capricho\n\nsi yo se que es a mi a quien quieres,\n\nno podras ser feliz con ningun otro\n\npues conmigo conociste el amor..\n\nsi el amor.. si el amooor\n\n\n\nTe he prometido que te he de olvidar\n\ncuanto has querido y yo te supe dar,\n\nsolo y herido asi me dejas,\n\nsabiendo que mañana iras con otro al altar\n\n\n\nLloraras, Lloraras por tu capricho\n\nsi yo se que es a mi a quien quieres,\n\nno podras ser feliz con ningun otro,\n\npues conmigo conociste el amor..\n\nsi el amor.. si el amooor!!!!!"
  },
  "como te extraño": {
     "letra":"Como te extraño mi amor por que sera\n\nme falta todo en la vida si no estas\n\ncomo te extraño mi amor que debeo hacer\n\nte extraño tanto que voy a enloquecer\n\n\n\nHay amor divino pronto tienes que volver a mi\n\n\n\nA veces pienso que tu nunca vendras\n\npero te quiero y te tengo que esperar\n\nes el destino me lleva hasta el final\n\ndonde algun mi amor te encontrara\n\n\n\nHay amor divino pronto tienes que volver a mi\n\n\n\nEl dolor es fuerte y lo soporto\n\npor que sufro pensando en tu amor\n\nquiero verte tenerte y besarte\n\ny entregarte todo mi corazon\n\n\n\nComo te extraño mi amor por que sera\n\nme falta todo en la vida si no estas\n\ncomo te extraño mi amor que debeo hacer\n\nte extraño tanto que voy a enloquecer"
  },
  "mary es mi amor": {
     "letra":"Mary es mi amor, solo con ella vivo la felicidad\n\nyo se que nunca a nadie mas podria amar, por que la quiero de verdad\n\npor eso mary por favor dame tu mano continuemos siempre asi\n\ndespues de todo que mas te puedo pedir\n\nsi soy feliz...muy feliz.\n\nSi un dia me faltas tu que Dios me ayude a morir\n\nya que no volvera a hacer en esta feliiiizzzz!!!!\n\nsin ti mary...sin ti mary...si estoy viviendo por ti\n\n\n\nMary es mi amor, solo con ella vivo la felicidad\n\nyo se que nunca nadie mas podria amar, por que la quiero de verdad.\n\nSi un dia me faltas tu que Dios me ayude a morir\n\nya que no volvera a hacer en esta feliiiizzzz\n\nsin ti mary...sin ti mary...si estoy viviendo por tiiiii!!"
  },
  "esa pared": {
     "letra":"Si pudiera estrecharte seria tan dichoso\n\nel mundo mas hermoso lo vería por ti\n\npero no se que hay entre nosotros\n\nque me separa cada día mas de ti\n\n\n\nesa pared,\n\nque no me deja verte\n\ndebe caer por obras del amor\n\n\n\nesa pared,\n\nque nos separa siempre\n\ndebe caer debemos platicar\n\n\n\nlas horas que pensando estoy en ti\n\nse hacen eternas\n\ncomo es posible que tu ni comprendas cuanto te quiero y mi corazón\n\nsera tan feliz\n\n\n\n¡si tu eres mia!\n\n¡si tu eres mia!"
  },
  "amos divino": {
     "letra":"Como te extraño mi amor, por que sera?\n\nMe falta todo en la vida si no estas\n\nComo te extraño mi amor, que debo hacer?\n\nTe extraño tanto que voy a enloquecer\n\n\n\nAy amor divino, pronto tienes que volveeer ami\n\n\n\nAveces pienso que tu nunca vendras\n\nPero te quiero y te tengo que esperar\n\nEs el destino me lleva hasta el final\n\nDonde algun dia mi amor te encontrará\n\n\n\nAy amor divino, pronto tienes que volveeer ami\n\n\n\nEl dolor es fuerte y lo soporto\n\npor que sufro pensando en tu amor\n\nquiero verte, tenerte y besarte\n\ny entregarte todo mi corazon\n\n\n\nComo te extraño mi amor, por que sera?\n\nMe falta todo en la vida si no estas\n\nComo te extraño mi amor, que debo hacer?\n\nTe extraño tanto que voy a enloquecer"
  },
  "la niña esta triste": {
     "letra":"La niña triste \n\nque tiene la niña \n\nque puedo yo hacer \n\npara que sonría. \n\n\n\nNo puedo reírme \n\nme dijo la niña \n\nmi amor a muerto \n\ny muerto mi vida. \n\n\n\nCoro… \n\nSeñor… \n\nayúdala dios mío \n\npor que a ella yo la quier\n\n con todo mi corazón. \n\n\n\nSeñor… \n\nte pido que la ayudes \n\nes mi niña y en su alma\n\nno tiene que haber dolor. \n\n\n\nNo quisiera nunca \n\nverte triste niña \n\nnunca verte triste \n\namor de mi vida. \n\n\n\nCoro… \n\n\n\nLa niña triste \n\nque tiene la niña \n\nque puedo yo hacer \n\npara que sonría. \n\n\n\nLa niña triste \n\nque tiene la niña \n\nque puedo yo hacer \n\npara que sonría."
  },
  "lloraras (leo dan)": {
     "letra":"Te he prometido que te he de olvidar\n\ncuanto has querido yo te supe dar\n\nsolo y herido asi me dejas\n\nsabiendo que mañana iras con otro al altar\n\n\n\nLloraras, Lloraras por tu capricho\n\nsi yo se que es a mi a quien quieres\n\nno podras ser feliz con ningun otro\n\npues conmigo conociste el amor\n\nsi el amor, si el amor\n\n\n\nSi volvieran los ojos atrás hasta que en el momento en que nos conocimos\n\nsi recordaras tu primera sonrisa hacia a mi\n\nestoy tan seguro que te encontrarias con tu verdadero amor\n\ncomo yo lo encontré en ti\n\n\n\nTe he prometido que te he de olvidar\n\ncuanto has querido yo te supe dar\n\nsolo y herido asi me dejas\n\nsabiendo que mañana iras con otro al altar\n\n\n\nLloraras, Lloraras por tu capricho\n\nsi yo se que es a mi a quien quieres\n\nno podras ser feliz con ningun otro\n\npues conmigo conociste el amor\n\nsi el amor, si el amor"
  },
  "toquen mariachis canten": {
     "letra":"Adiós, adiós, mi México lindo\n\nmañana, mañana me iré,\n\nadiós, adiós México querido,\n\nyo nunca olvidarte podré.\n\nToquen mariachis, canten\n\nalegren mi corazón,\n\nno quiero que nadie me vea triste\n\nque nadie sepa de mi dolor.\n\nCaminos que me esperan,\n\nno me dejen sin volver,\n\nporque aquí una madrecita buena\n\nme está pidiendo me vaya bien.\n\nAdiós, adiós mi México lindo\n\nMañana, mañana me iré\n\nAdiós adiós México querido\n\nYo nunca olvidarte podré\n\nfronteras, porque fronteras\n\nsi en mi música hay amor,\n\nnadie podrá nunca en la idea\n\nponer fronteras, tan sólo Dios.\n\n\n\nToquen mariachis, canten,\n\nque el mundo escuche su voz\n\nporque mientras cante el mundo entero\n\nno habrá mas guerras, sino canciones (x3),"
  }
}

let fff=Object.keys(ff);


 const fs=require('fs');



            fs.appendFile('vargass.json', fff, (error)=>{  
            if(error){
               throw error;
            }
            console.log("todo bien");
            });